# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1815, 914)
        MainWindow.setWindowOpacity(1.000000000000000)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1811, 921))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0.03, y1:0.955, x2:1, y2:0, stop:0 rgba(175, 175, 175, 57), stop:1 rgba(255, 255, 255, 255))")
        self.control_tab = QWidget()
        self.control_tab.setObjectName(u"control_tab")
        self.frame1 = QFrame(self.control_tab)
        self.frame1.setObjectName(u"frame1")
        self.frame1.setGeometry(QRect(0, 0, 901, 301))
        self.frame1.setFrameShape(QFrame.StyledPanel)
        self.frame1.setFrameShadow(QFrame.Plain)
        self.groupBox_1 = QGroupBox(self.frame1)
        self.groupBox_1.setObjectName(u"groupBox_1")
        self.groupBox_1.setGeometry(QRect(10, 20, 201, 271))
        font = QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox_1.setFont(font)
        self.com_label = QLabel(self.groupBox_1)
        self.com_label.setObjectName(u"com_label")
        self.com_label.setGeometry(QRect(10, 30, 55, 31))
        font1 = QFont()
        font1.setPointSize(9)
        font1.setBold(False)
        font1.setUnderline(False)
        font1.setWeight(50)
        self.com_label.setFont(font1)
        self.com_label.setLayoutDirection(Qt.LeftToRight)
        self.com_label.setStyleSheet(u"background: transparent;")
        self.baud_label = QLabel(self.groupBox_1)
        self.baud_label.setObjectName(u"baud_label")
        self.baud_label.setGeometry(QRect(10, 75, 81, 21))
        self.baud_label.setFont(font1)
        self.baud_label.setStyleSheet(u"background: transparent;")
        self.btn_cnt = QPushButton(self.groupBox_1)
        self.btn_cnt.setObjectName(u"btn_cnt")
        self.btn_cnt.setGeometry(QRect(40, 120, 101, 41))
        self.btn_cnt.setFont(font1)
        self.btn_cnt.setStyleSheet(u"")
        self.cb_com = QComboBox(self.groupBox_1)
        self.cb_com.setObjectName(u"cb_com")
        self.cb_com.setGeometry(QRect(90, 30, 101, 31))
        font2 = QFont()
        font2.setBold(False)
        font2.setWeight(50)
        self.cb_com.setFont(font2)
        self.cb_baudrate = QComboBox(self.groupBox_1)
        self.cb_baudrate.setObjectName(u"cb_baudrate")
        self.cb_baudrate.setGeometry(QRect(90, 70, 101, 31))
        self.cb_baudrate.setFont(font2)
        self.light_stt = QLabel(self.groupBox_1)
        self.light_stt.setObjectName(u"light_stt")
        self.light_stt.setGeometry(QRect(70, 170, 41, 41))
        self.light_stt.setStyleSheet(u"background: rgb(255,0,0); border-radius:20px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width : 0.5px;\n"
"border-style:inset;")
        self.text_stt = QLabel(self.groupBox_1)
        self.text_stt.setObjectName(u"text_stt")
        self.text_stt.setGeometry(QRect(40, 220, 101, 31))
        font3 = QFont()
        font3.setPointSize(10)
        font3.setBold(False)
        font3.setUnderline(False)
        font3.setWeight(50)
        self.text_stt.setFont(font3)
        self.text_stt.setFrameShape(QFrame.WinPanel)
        self.text_stt.setFrameShadow(QFrame.Sunken)
        self.text_stt.setAlignment(Qt.AlignCenter)
        self.groupBox_7 = QGroupBox(self.frame1)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setEnabled(True)
        self.groupBox_7.setGeometry(QRect(220, 20, 221, 271))
        font4 = QFont()
        font4.setPointSize(9)
        font4.setBold(True)
        font4.setWeight(75)
        self.groupBox_7.setFont(font4)
        self.btn_calibJ1 = QPushButton(self.groupBox_7)
        self.btn_calibJ1.setObjectName(u"btn_calibJ1")
        self.btn_calibJ1.setGeometry(QRect(40, 30, 151, 31))
        font5 = QFont()
        font5.setPointSize(9)
        font5.setBold(False)
        font5.setWeight(50)
        self.btn_calibJ1.setFont(font5)
        self.btn_calibJ1.setAutoDefault(True)
        self.btn_calibJ2 = QPushButton(self.groupBox_7)
        self.btn_calibJ2.setObjectName(u"btn_calibJ2")
        self.btn_calibJ2.setGeometry(QRect(40, 80, 151, 31))
        self.btn_calibJ2.setFont(font5)
        self.btn_calibJ2.setAutoDefault(True)
        self.btn_calibJ3 = QPushButton(self.groupBox_7)
        self.btn_calibJ3.setObjectName(u"btn_calibJ3")
        self.btn_calibJ3.setGeometry(QRect(40, 130, 151, 31))
        self.btn_calibJ3.setFont(font5)
        self.btn_calibJ3.setAutoDefault(True)
        self.btn_Home = QPushButton(self.groupBox_7)
        self.btn_Home.setObjectName(u"btn_Home")
        self.btn_Home.setGeometry(QRect(40, 180, 151, 31))
        self.btn_Home.setFont(font5)
        self.btn_Home.setAutoDefault(True)
        self.btn_calibHome = QPushButton(self.groupBox_7)
        self.btn_calibHome.setObjectName(u"btn_calibHome")
        self.btn_calibHome.setGeometry(QRect(40, 230, 151, 31))
        self.btn_calibHome.setFont(font5)
        self.btn_calibHome.setAutoDefault(True)
        self.groupBox_6 = QGroupBox(self.frame1)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(450, 20, 441, 271))
        self.groupBox_6.setFont(font4)
        self.label_15 = QLabel(self.groupBox_6)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 40, 131, 16))
        self.label_15.setFont(font5)
        self.label_15.setStyleSheet(u"background: transparent;")
        self.slide_speed = QSlider(self.groupBox_6)
        self.slide_speed.setObjectName(u"slide_speed")
        self.slide_speed.setGeometry(QRect(20, 70, 211, 22))
        self.slide_speed.setStyleSheet(u"background: transparent;")
        self.slide_speed.setMaximum(40000)
        self.slide_speed.setSingleStep(2000)
        self.slide_speed.setPageStep(10)
        self.slide_speed.setValue(20000)
        self.slide_speed.setSliderPosition(20000)
        self.slide_speed.setOrientation(Qt.Horizontal)
        self.slide_speed.setTickPosition(QSlider.TicksBelow)
        self.slide_speed.setTickInterval(2000)
        self.btn_apply = QPushButton(self.groupBox_6)
        self.btn_apply.setObjectName(u"btn_apply")
        self.btn_apply.setGeometry(QRect(120, 210, 151, 41))
        self.btn_apply.setFont(font5)
        self.btn_apply.setIconSize(QSize(20, 20))
        self.btn_apply.setAutoDefault(True)
        self.label_35 = QLabel(self.groupBox_6)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(20, 130, 171, 16))
        self.label_35.setFont(font5)
        self.label_35.setStyleSheet(u"background: transparent;")
        self.slide_acc = QSlider(self.groupBox_6)
        self.slide_acc.setObjectName(u"slide_acc")
        self.slide_acc.setGeometry(QRect(20, 160, 211, 22))
        self.slide_acc.setStyleSheet(u"background: transparent;")
        self.slide_acc.setMaximum(40000)
        self.slide_acc.setSingleStep(2000)
        self.slide_acc.setValue(20000)
        self.slide_acc.setOrientation(Qt.Horizontal)
        self.slide_acc.setTickPosition(QSlider.TicksBelow)
        self.slide_acc.setTickInterval(2000)
        self.light_stt_sp = QLabel(self.groupBox_6)
        self.light_stt_sp.setObjectName(u"light_stt_sp")
        self.light_stt_sp.setGeometry(QRect(240, 60, 31, 31))
        self.light_stt_sp.setStyleSheet(u"background: rgb(0,255,0); border-radius:10px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width : 0.5px;\n"
"border-style:inset;")
        self.light_stt_acc = QLabel(self.groupBox_6)
        self.light_stt_acc.setObjectName(u"light_stt_acc")
        self.light_stt_acc.setGeometry(QRect(240, 150, 31, 31))
        self.light_stt_acc.setStyleSheet(u"background: rgb(0,255,0); border-radius:10px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width : 0.5px;\n"
"border-style:inset;")
        self.listView = QListView(self.groupBox_6)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(310, 40, 121, 211))
        self.light_stt_sp_2 = QLabel(self.groupBox_6)
        self.light_stt_sp_2.setObjectName(u"light_stt_sp_2")
        self.light_stt_sp_2.setGeometry(QRect(320, 50, 31, 31))
        self.light_stt_sp_2.setStyleSheet(u"background:rgb(166, 254, 255); border-radius:10px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width : 0.5px;\n"
"border-style:inset;")
        self.light_stt_sp_3 = QLabel(self.groupBox_6)
        self.light_stt_sp_3.setObjectName(u"light_stt_sp_3")
        self.light_stt_sp_3.setGeometry(QRect(320, 90, 31, 31))
        self.light_stt_sp_3.setStyleSheet(u"background: rgb(21, 165, 255); border-radius:10px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width : 0.5px;\n"
"border-style:inset;")
        self.light_stt_sp_4 = QLabel(self.groupBox_6)
        self.light_stt_sp_4.setObjectName(u"light_stt_sp_4")
        self.light_stt_sp_4.setGeometry(QRect(320, 130, 31, 31))
        self.light_stt_sp_4.setStyleSheet(u"background: rgb(0,255,0); border-radius:10px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width : 0.5px;\n"
"border-style:inset;")
        self.light_stt_sp_5 = QLabel(self.groupBox_6)
        self.light_stt_sp_5.setObjectName(u"light_stt_sp_5")
        self.light_stt_sp_5.setGeometry(QRect(320, 170, 31, 31))
        self.light_stt_sp_5.setStyleSheet(u"background: rgb(255, 167, 15); border-radius:10px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width : 0.5px;\n"
"border-style:inset;")
        self.light_stt_sp_6 = QLabel(self.groupBox_6)
        self.light_stt_sp_6.setObjectName(u"light_stt_sp_6")
        self.light_stt_sp_6.setGeometry(QRect(320, 210, 31, 31))
        self.light_stt_sp_6.setStyleSheet(u"background: rgb(255,0,0); border-radius:10px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width : 0.5px;\n"
"border-style:inset;")
        self.label_33 = QLabel(self.groupBox_6)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(360, 60, 55, 16))
        self.label_33.setStyleSheet(u"background: transparent;")
        self.label_33.setAlignment(Qt.AlignCenter)
        self.label_36 = QLabel(self.groupBox_6)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(360, 140, 55, 16))
        self.label_36.setStyleSheet(u"background: transparent;")
        self.label_36.setAlignment(Qt.AlignCenter)
        self.label_45 = QLabel(self.groupBox_6)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(360, 100, 55, 16))
        self.label_45.setStyleSheet(u"background: transparent;")
        self.label_45.setAlignment(Qt.AlignCenter)
        self.label_49 = QLabel(self.groupBox_6)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(360, 180, 55, 16))
        self.label_49.setStyleSheet(u"background: transparent;")
        self.label_49.setAlignment(Qt.AlignCenter)
        self.label_51 = QLabel(self.groupBox_6)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(360, 220, 55, 16))
        self.label_51.setStyleSheet(u"background: transparent;")
        self.label_51.setAlignment(Qt.AlignCenter)
        self.frame_2 = QFrame(self.control_tab)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(0, 300, 901, 581))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Plain)
        self.groupBox_5 = QGroupBox(self.frame_2)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 10, 431, 251))
        self.groupBox_5.setFont(font4)
        self.label = QLabel(self.groupBox_5)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 100, 70, 30))
        self.label.setFont(font5)
        self.label.setStyleSheet(u"background: transparent;")
        self.label.setAlignment(Qt.AlignCenter)
        self.btn_j1_dec = QPushButton(self.groupBox_5)
        self.btn_j1_dec.setObjectName(u"btn_j1_dec")
        self.btn_j1_dec.setGeometry(QRect(90, 100, 100, 30))
        icon = QIcon()
        icon.addFile(u"GUI/icon_phai.PNG", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_j1_dec.setIcon(icon)
        self.btn_j1_dec.setIconSize(QSize(20, 20))
        self.btn_j1_inc = QPushButton(self.groupBox_5)
        self.btn_j1_inc.setObjectName(u"btn_j1_inc")
        self.btn_j1_inc.setGeometry(QRect(310, 100, 100, 30))
        icon1 = QIcon()
        icon1.addFile(u"GUI/icon_trai.PNG", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_j1_inc.setIcon(icon1)
        self.btn_j1_inc.setIconSize(QSize(20, 20))
        self.btn_j2_inc = QPushButton(self.groupBox_5)
        self.btn_j2_inc.setObjectName(u"btn_j2_inc")
        self.btn_j2_inc.setGeometry(QRect(310, 150, 100, 30))
        self.btn_j2_inc.setIcon(icon1)
        self.btn_j2_inc.setIconSize(QSize(20, 20))
        self.txt_j2 = QTextEdit(self.groupBox_5)
        self.txt_j2.setObjectName(u"txt_j2")
        self.txt_j2.setGeometry(QRect(200, 150, 100, 30))
        self.txt_j2.setFont(font5)
        self.txt_j2.setReadOnly(True)
        self.label_2 = QLabel(self.groupBox_5)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 150, 70, 30))
        self.label_2.setFont(font5)
        self.label_2.setStyleSheet(u"background: transparent;")
        self.label_2.setAlignment(Qt.AlignCenter)
        self.btn_j2_dec = QPushButton(self.groupBox_5)
        self.btn_j2_dec.setObjectName(u"btn_j2_dec")
        self.btn_j2_dec.setGeometry(QRect(90, 150, 100, 30))
        self.btn_j2_dec.setIcon(icon)
        self.btn_j2_dec.setIconSize(QSize(20, 20))
        self.btn_j3_inc = QPushButton(self.groupBox_5)
        self.btn_j3_inc.setObjectName(u"btn_j3_inc")
        self.btn_j3_inc.setGeometry(QRect(310, 200, 100, 30))
        self.btn_j3_inc.setIcon(icon1)
        self.btn_j3_inc.setIconSize(QSize(20, 20))
        self.txt_j3 = QTextEdit(self.groupBox_5)
        self.txt_j3.setObjectName(u"txt_j3")
        self.txt_j3.setGeometry(QRect(200, 200, 100, 30))
        self.txt_j3.setFont(font5)
        self.txt_j3.setReadOnly(True)
        self.label_3 = QLabel(self.groupBox_5)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 200, 70, 30))
        self.label_3.setFont(font5)
        self.label_3.setStyleSheet(u"background: transparent;")
        self.label_3.setAlignment(Qt.AlignCenter)
        self.btn_j3_dec = QPushButton(self.groupBox_5)
        self.btn_j3_dec.setObjectName(u"btn_j3_dec")
        self.btn_j3_dec.setGeometry(QRect(90, 200, 100, 30))
        self.btn_j3_dec.setIcon(icon)
        self.btn_j3_dec.setIconSize(QSize(20, 20))
        self.label_28 = QLabel(self.groupBox_5)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(140, 30, 141, 16))
        self.label_28.setFont(font5)
        self.slide_deg = QSlider(self.groupBox_5)
        self.slide_deg.setObjectName(u"slide_deg")
        self.slide_deg.setGeometry(QRect(110, 60, 191, 22))
        self.slide_deg.setFont(font5)
        self.slide_deg.setStyleSheet(u"background: transparent;")
        self.slide_deg.setMaximum(20)
        self.slide_deg.setSingleStep(5)
        self.slide_deg.setOrientation(Qt.Horizontal)
        self.slide_deg.setTickPosition(QSlider.TicksBelow)
        self.slide_deg.setTickInterval(5)
        self.label_30 = QLabel(self.groupBox_5)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(370, 50, 31, 31))
        self.label_30.setFont(font5)
        self.label_30.setStyleSheet(u"background: transparent;")
        self.txt_deg = QTextEdit(self.groupBox_5)
        self.txt_deg.setObjectName(u"txt_deg")
        self.txt_deg.setGeometry(QRect(310, 50, 51, 28))
        self.txt_deg.setFont(font5)
        self.txt_deg.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_deg.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_deg.setReadOnly(True)
        self.txt_j1 = QTextEdit(self.groupBox_5)
        self.txt_j1.setObjectName(u"txt_j1")
        self.txt_j1.setGeometry(QRect(200, 100, 101, 28))
        self.txt_j1.setFont(font5)
        self.txt_j1.setReadOnly(True)
        self.groupBox_3 = QGroupBox(self.frame_2)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(450, 10, 441, 251))
        self.groupBox_3.setFont(font4)
        self.groupBox_3.setAutoFillBackground(False)
        self.label_4 = QLabel(self.groupBox_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 100, 70, 30))
        self.label_4.setFont(font5)
        self.label_4.setStyleSheet(u"background: transparent;")
        self.label_4.setAlignment(Qt.AlignCenter)
        self.btn_x_dec = QPushButton(self.groupBox_3)
        self.btn_x_dec.setObjectName(u"btn_x_dec")
        self.btn_x_dec.setGeometry(QRect(80, 100, 100, 30))
        self.btn_x_dec.setIcon(icon)
        self.btn_x_dec.setIconSize(QSize(20, 20))
        self.txt_x = QTextEdit(self.groupBox_3)
        self.txt_x.setObjectName(u"txt_x")
        self.txt_x.setGeometry(QRect(190, 100, 100, 30))
        self.txt_x.setFont(font5)
        self.txt_x.setReadOnly(True)
        self.btn_x_inc = QPushButton(self.groupBox_3)
        self.btn_x_inc.setObjectName(u"btn_x_inc")
        self.btn_x_inc.setGeometry(QRect(300, 100, 100, 30))
        self.btn_x_inc.setIcon(icon1)
        self.btn_x_inc.setIconSize(QSize(20, 20))
        self.btn_y_inc = QPushButton(self.groupBox_3)
        self.btn_y_inc.setObjectName(u"btn_y_inc")
        self.btn_y_inc.setGeometry(QRect(300, 150, 100, 30))
        self.btn_y_inc.setIcon(icon1)
        self.btn_y_inc.setIconSize(QSize(20, 20))
        self.txt_y = QTextEdit(self.groupBox_3)
        self.txt_y.setObjectName(u"txt_y")
        self.txt_y.setGeometry(QRect(190, 150, 100, 30))
        self.txt_y.setFont(font5)
        self.txt_y.setReadOnly(True)
        self.label_5 = QLabel(self.groupBox_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 150, 70, 30))
        self.label_5.setFont(font5)
        self.label_5.setStyleSheet(u"background: transparent;")
        self.label_5.setAlignment(Qt.AlignCenter)
        self.btn_y_dec = QPushButton(self.groupBox_3)
        self.btn_y_dec.setObjectName(u"btn_y_dec")
        self.btn_y_dec.setGeometry(QRect(80, 150, 100, 30))
        self.btn_y_dec.setIcon(icon)
        self.btn_y_dec.setIconSize(QSize(20, 20))
        self.btn_z_inc = QPushButton(self.groupBox_3)
        self.btn_z_inc.setObjectName(u"btn_z_inc")
        self.btn_z_inc.setGeometry(QRect(300, 200, 100, 30))
        self.btn_z_inc.setIcon(icon1)
        self.btn_z_inc.setIconSize(QSize(20, 20))
        self.txt_z = QTextEdit(self.groupBox_3)
        self.txt_z.setObjectName(u"txt_z")
        self.txt_z.setGeometry(QRect(190, 200, 100, 30))
        self.txt_z.setFont(font5)
        self.txt_z.setReadOnly(True)
        self.label_6 = QLabel(self.groupBox_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 200, 70, 30))
        self.label_6.setFont(font5)
        self.label_6.setStyleSheet(u"background: transparent;")
        self.label_6.setAlignment(Qt.AlignCenter)
        self.btn_z_dec = QPushButton(self.groupBox_3)
        self.btn_z_dec.setObjectName(u"btn_z_dec")
        self.btn_z_dec.setGeometry(QRect(80, 200, 100, 30))
        self.btn_z_dec.setIcon(icon)
        self.btn_z_dec.setIconSize(QSize(20, 20))
        self.label_37 = QLabel(self.groupBox_3)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(130, 30, 141, 16))
        self.label_37.setFont(font5)
        self.label_29 = QLabel(self.groupBox_3)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(360, 50, 31, 31))
        self.label_29.setFont(font5)
        self.label_29.setStyleSheet(u"background: transparent;")
        self.slide_cm = QSlider(self.groupBox_3)
        self.slide_cm.setObjectName(u"slide_cm")
        self.slide_cm.setGeometry(QRect(100, 60, 191, 22))
        self.slide_cm.setFont(font5)
        self.slide_cm.setMaximum(5)
        self.slide_cm.setOrientation(Qt.Horizontal)
        self.slide_cm.setTickPosition(QSlider.TicksBelow)
        self.slide_cm.setTickInterval(1)
        self.txt_cm = QTextEdit(self.groupBox_3)
        self.txt_cm.setObjectName(u"txt_cm")
        self.txt_cm.setGeometry(QRect(300, 50, 51, 28))
        self.txt_cm.setFont(font5)
        self.txt_cm.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_cm.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_cm.setReadOnly(True)
        self.groupBox_4 = QGroupBox(self.frame_2)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 270, 381, 301))
        self.groupBox_4.setFont(font4)
        self.groupBox_4.setAutoFillBackground(False)
        self.cb_sizetype = QComboBox(self.groupBox_4)
        self.cb_sizetype.setObjectName(u"cb_sizetype")
        self.cb_sizetype.setGeometry(QRect(80, 60, 91, 31))
        self.cb_sizetype.setFont(font2)
        self.label_7 = QLabel(self.groupBox_4)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(80, 30, 71, 16))
        self.label_7.setFont(font2)
        self.label_7.setStyleSheet(u"background: transparent;")
        self.btn_savepoint = QPushButton(self.groupBox_4)
        self.btn_savepoint.setObjectName(u"btn_savepoint")
        self.btn_savepoint.setGeometry(QRect(190, 60, 81, 31))
        self.btn_savepoint.setFont(font2)
        self.rbutton_new = QRadioButton(self.groupBox_4)
        self.rbutton_new.setObjectName(u"rbutton_new")
        self.rbutton_new.setGeometry(QRect(190, 30, 171, 20))
        font6 = QFont()
        font6.setFamily(u"Nirmala UI")
        font6.setBold(True)
        font6.setWeight(75)
        self.rbutton_new.setFont(font6)
        self.rbutton_new.setCursor(QCursor(Qt.PointingHandCursor))
        self.txt_info_teaching = QTextBrowser(self.groupBox_4)
        self.txt_info_teaching.setObjectName(u"txt_info_teaching")
        self.txt_info_teaching.setGeometry(QRect(10, 110, 351, 171))
        font7 = QFont()
        font7.setPointSize(10)
        font7.setBold(False)
        font7.setWeight(50)
        self.txt_info_teaching.setFont(font7)
        self.txt_info_teaching.setStyleSheet(u"background: transparent;")
        self.txt_info_teaching.setFrameShape(QFrame.WinPanel)
        self.txt_info_teaching.setFrameShadow(QFrame.Plain)
        self.txt_info_teaching.setLineWidth(1)
        self.txt_info_teaching.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_info_teaching.setReadOnly(True)
        self.cb_point = QComboBox(self.groupBox_4)
        self.cb_point.setObjectName(u"cb_point")
        self.cb_point.setGeometry(QRect(10, 60, 61, 31))
        self.cb_point.setFont(font2)
        self.label_21 = QLabel(self.groupBox_4)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 30, 41, 16))
        self.label_21.setFont(font2)
        self.label_21.setStyleSheet(u"background: transparent;")
        self.btn_reset_point = QPushButton(self.groupBox_4)
        self.btn_reset_point.setObjectName(u"btn_reset_point")
        self.btn_reset_point.setGeometry(QRect(280, 60, 81, 31))
        self.btn_reset_point.setFont(font2)
        self.groupBox_8 = QGroupBox(self.frame_2)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(400, 270, 251, 301))
        self.groupBox_8.setFont(font4)
        self.groupBox_8.setAutoFillBackground(False)
        self.label_8 = QLabel(self.groupBox_8)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(40, 35, 41, 21))
        self.label_8.setFont(font5)
        self.label_8.setStyleSheet(u"background: transparent;")
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(self.groupBox_8)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(40, 80, 41, 21))
        self.label_9.setFont(font5)
        self.label_9.setStyleSheet(u"background: transparent;")
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_10 = QLabel(self.groupBox_8)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(40, 125, 41, 21))
        self.label_10.setFont(font5)
        self.label_10.setStyleSheet(u"background: transparent;")
        self.label_10.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(self.groupBox_8)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(40, 170, 41, 21))
        self.label_11.setFont(font5)
        self.label_11.setStyleSheet(u"background: transparent;")
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_12 = QLabel(self.groupBox_8)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(40, 210, 41, 31))
        self.label_12.setFont(font5)
        self.label_12.setStyleSheet(u"background: transparent;")
        self.label_12.setAlignment(Qt.AlignCenter)
        self.label_13 = QLabel(self.groupBox_8)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(40, 260, 41, 21))
        self.label_13.setFont(font5)
        self.label_13.setStyleSheet(u"background: transparent;")
        self.label_13.setAlignment(Qt.AlignCenter)
        self.txt_cX = QTextEdit(self.groupBox_8)
        self.txt_cX.setObjectName(u"txt_cX")
        self.txt_cX.setGeometry(QRect(80, 30, 81, 31))
        self.txt_cX.setFont(font5)
        self.txt_cX.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_cX.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_cX.setReadOnly(True)
        self.label_14 = QLabel(self.groupBox_8)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(160, 30, 41, 31))
        self.label_14.setFont(font5)
        self.label_14.setStyleSheet(u"background: transparent;")
        self.label_14.setAlignment(Qt.AlignCenter)
        self.label_22 = QLabel(self.groupBox_8)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(160, 80, 41, 21))
        self.label_22.setFont(font5)
        self.label_22.setStyleSheet(u"background: transparent;")
        self.label_22.setAlignment(Qt.AlignCenter)
        self.label_23 = QLabel(self.groupBox_8)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(160, 125, 41, 21))
        self.label_23.setFont(font5)
        self.label_23.setStyleSheet(u"background: transparent;")
        self.label_23.setAlignment(Qt.AlignCenter)
        self.txt_cZ = QTextEdit(self.groupBox_8)
        self.txt_cZ.setObjectName(u"txt_cZ")
        self.txt_cZ.setGeometry(QRect(80, 120, 81, 31))
        self.txt_cZ.setFont(font5)
        self.txt_cZ.setReadOnly(True)
        self.txt_cY = QTextEdit(self.groupBox_8)
        self.txt_cY.setObjectName(u"txt_cY")
        self.txt_cY.setGeometry(QRect(80, 75, 81, 31))
        self.txt_cY.setFont(font5)
        self.txt_cY.setReadOnly(True)
        self.label_24 = QLabel(self.groupBox_8)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(160, 160, 41, 41))
        self.label_24.setFont(font5)
        self.label_24.setStyleSheet(u"background: transparent;")
        self.label_24.setAlignment(Qt.AlignCenter)
        self.txt_cRoll = QTextEdit(self.groupBox_8)
        self.txt_cRoll.setObjectName(u"txt_cRoll")
        self.txt_cRoll.setGeometry(QRect(80, 165, 81, 31))
        self.txt_cRoll.setFont(font5)
        self.txt_cRoll.setReadOnly(True)
        self.label_25 = QLabel(self.groupBox_8)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(160, 210, 41, 31))
        self.label_25.setFont(font5)
        self.label_25.setStyleSheet(u"background: transparent;")
        self.label_25.setAlignment(Qt.AlignCenter)
        self.txt_cPitch = QTextEdit(self.groupBox_8)
        self.txt_cPitch.setObjectName(u"txt_cPitch")
        self.txt_cPitch.setGeometry(QRect(80, 210, 81, 31))
        self.txt_cPitch.setFont(font5)
        self.txt_cPitch.setReadOnly(True)
        self.label_26 = QLabel(self.groupBox_8)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(160, 250, 41, 41))
        self.label_26.setFont(font5)
        self.label_26.setStyleSheet(u"background: transparent;")
        self.label_26.setAlignment(Qt.AlignCenter)
        self.txt_cYaw = QTextEdit(self.groupBox_8)
        self.txt_cYaw.setObjectName(u"txt_cYaw")
        self.txt_cYaw.setGeometry(QRect(80, 255, 81, 31))
        self.txt_cYaw.setFont(font5)
        self.txt_cYaw.setReadOnly(True)
        self.label_26.raise_()
        self.label_25.raise_()
        self.label_24.raise_()
        self.label_23.raise_()
        self.label_22.raise_()
        self.label_14.raise_()
        self.label_10.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_13.raise_()
        self.label_12.raise_()
        self.label_11.raise_()
        self.txt_cX.raise_()
        self.txt_cZ.raise_()
        self.txt_cY.raise_()
        self.txt_cRoll.raise_()
        self.txt_cPitch.raise_()
        self.txt_cYaw.raise_()
        self.groupBox_2 = QGroupBox(self.frame_2)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(660, 270, 231, 211))
        self.groupBox_2.setFont(font4)
        self.label_17 = QLabel(self.groupBox_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(40, 80, 41, 21))
        self.label_17.setFont(font5)
        self.label_17.setStyleSheet(u"background: transparent;")
        self.label_17.setAlignment(Qt.AlignCenter)
        self.txt_mY = QTextEdit(self.groupBox_2)
        self.txt_mY.setObjectName(u"txt_mY")
        self.txt_mY.setGeometry(QRect(80, 75, 81, 31))
        self.txt_mY.setFont(font5)
        self.txt_mY.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_mY.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_mX = QTextEdit(self.groupBox_2)
        self.txt_mX.setObjectName(u"txt_mX")
        self.txt_mX.setGeometry(QRect(80, 30, 81, 31))
        self.txt_mX.setFont(font5)
        self.txt_mX.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_mX.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.label_27 = QLabel(self.groupBox_2)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(160, 80, 41, 21))
        self.label_27.setFont(font5)
        self.label_27.setStyleSheet(u"background: transparent;")
        self.label_27.setAlignment(Qt.AlignCenter)
        self.label_18 = QLabel(self.groupBox_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(40, 35, 41, 21))
        self.label_18.setFont(font5)
        self.label_18.setStyleSheet(u"background: transparent;")
        self.label_18.setAlignment(Qt.AlignCenter)
        self.txt_mZ = QTextEdit(self.groupBox_2)
        self.txt_mZ.setObjectName(u"txt_mZ")
        self.txt_mZ.setGeometry(QRect(80, 120, 81, 31))
        self.txt_mZ.setFont(font5)
        self.txt_mZ.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_mZ.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.label_19 = QLabel(self.groupBox_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(160, 35, 41, 21))
        self.label_19.setFont(font5)
        self.label_19.setStyleSheet(u"background: transparent;")
        self.label_19.setAlignment(Qt.AlignCenter)
        self.label_20 = QLabel(self.groupBox_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(40, 125, 41, 21))
        self.label_20.setFont(font5)
        self.label_20.setStyleSheet(u"background: transparent;")
        self.label_20.setAlignment(Qt.AlignCenter)
        self.label_38 = QLabel(self.groupBox_2)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(160, 125, 41, 21))
        self.label_38.setFont(font5)
        self.label_38.setStyleSheet(u"background: transparent;")
        self.label_38.setAlignment(Qt.AlignCenter)
        self.btn_move = QPushButton(self.groupBox_2)
        self.btn_move.setObjectName(u"btn_move")
        self.btn_move.setGeometry(QRect(70, 160, 100, 41))
        self.btn_move.setFont(font5)
        self.btn_move.setIconSize(QSize(20, 20))
        self.btn_move.setAutoDefault(True)
        self.label_20.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_38.raise_()
        self.label_27.raise_()
        self.txt_mY.raise_()
        self.txt_mX.raise_()
        self.txt_mZ.raise_()
        self.btn_move.raise_()
        self.groupBox_13 = QGroupBox(self.frame_2)
        self.groupBox_13.setObjectName(u"groupBox_13")
        self.groupBox_13.setGeometry(QRect(660, 490, 231, 80))
        self.groupBox_13.setFont(font4)
        self.btn_end_effector = QPushButton(self.groupBox_13)
        self.btn_end_effector.setObjectName(u"btn_end_effector")
        self.btn_end_effector.setEnabled(True)
        self.btn_end_effector.setGeometry(QRect(70, 30, 101, 41))
        self.btn_end_effector.setFont(font5)
        self.frame_3 = QFrame(self.control_tab)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(900, 0, 901, 881))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Plain)
        self.frame_7 = QFrame(self.frame_3)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(10, 340, 331, 331))
        self.frame_7.setFrameShape(QFrame.WinPanel)
        self.frame_7.setFrameShadow(QFrame.Plain)
        self.label_31 = QLabel(self.frame_7)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 10, 171, 41))
        font8 = QFont()
        font8.setFamily(u"Montserrat")
        font8.setPointSize(10)
        font8.setBold(True)
        font8.setUnderline(False)
        font8.setWeight(75)
        self.label_31.setFont(font8)
        self.label_31.setStyleSheet(u"background: #ff0000\n"
"")
        self.label_31.setFrameShape(QFrame.Box)
        self.label_31.setAlignment(Qt.AlignCenter)
        self.label_32 = QLabel(self.frame_7)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(20, 60, 41, 31))
        font9 = QFont()
        font9.setPointSize(9)
        font9.setBold(True)
        font9.setUnderline(False)
        font9.setWeight(75)
        font9.setStrikeOut(False)
        self.label_32.setFont(font9)
        self.label_32.setStyleSheet(u"background: transparent;")
        self.label_34 = QLabel(self.frame_7)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(160, 60, 51, 31))
        font10 = QFont()
        font10.setPointSize(9)
        font10.setBold(True)
        font10.setUnderline(False)
        font10.setWeight(75)
        self.label_34.setFont(font10)
        self.label_34.setStyleSheet(u"background: transparent;")
        self.label_40 = QLabel(self.frame_7)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(20, 110, 111, 31))
        self.label_40.setFont(font10)
        self.label_40.setStyleSheet(u"background: transparent;")
        self.label_41 = QLabel(self.frame_7)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(20, 160, 91, 31))
        self.label_41.setFont(font10)
        self.label_41.setStyleSheet(u"background: transparent;")
        self.label_42 = QLabel(self.frame_7)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(20, 210, 91, 31))
        self.label_42.setFont(font10)
        self.label_42.setStyleSheet(u"background: transparent;")
        self.res_size = QLabel(self.frame_7)
        self.res_size.setObjectName(u"res_size")
        self.res_size.setGeometry(QRect(60, 60, 91, 31))
        font11 = QFont()
        font11.setFamily(u"MS Shell Dlg 2")
        font11.setPointSize(9)
        self.res_size.setFont(font11)
        self.res_size.setFrameShape(QFrame.WinPanel)
        self.res_size.setFrameShadow(QFrame.Sunken)
        self.res_size.setAlignment(Qt.AlignCenter)
        self.res_color = QLabel(self.frame_7)
        self.res_color.setObjectName(u"res_color")
        self.res_color.setGeometry(QRect(210, 60, 101, 31))
        font12 = QFont()
        font12.setPointSize(9)
        self.res_color.setFont(font12)
        self.res_color.setFrameShape(QFrame.WinPanel)
        self.res_color.setFrameShadow(QFrame.Sunken)
        self.res_color.setAlignment(Qt.AlignCenter)
        self.result = QLabel(self.frame_7)
        self.result.setObjectName(u"result")
        self.result.setGeometry(QRect(130, 110, 181, 31))
        self.result.setFont(font12)
        self.result.setFrameShape(QFrame.WinPanel)
        self.result.setFrameShadow(QFrame.Sunken)
        self.result.setAlignment(Qt.AlignCenter)
        self.pick_pl = QLabel(self.frame_7)
        self.pick_pl.setObjectName(u"pick_pl")
        self.pick_pl.setGeometry(QRect(110, 160, 201, 31))
        self.pick_pl.setFont(font12)
        self.pick_pl.setFrameShape(QFrame.WinPanel)
        self.pick_pl.setFrameShadow(QFrame.Sunken)
        self.drop_pl = QLabel(self.frame_7)
        self.drop_pl.setObjectName(u"drop_pl")
        self.drop_pl.setGeometry(QRect(110, 210, 201, 31))
        self.drop_pl.setFont(font12)
        self.drop_pl.setFrameShape(QFrame.WinPanel)
        self.drop_pl.setFrameShadow(QFrame.Sunken)
        self.lb_info = QLabel(self.frame_7)
        self.lb_info.setObjectName(u"lb_info")
        self.lb_info.setGeometry(QRect(10, 260, 311, 61))
        font13 = QFont()
        font13.setPointSize(9)
        font13.setItalic(False)
        self.lb_info.setFont(font13)
        self.lb_info.setFocusPolicy(Qt.ClickFocus)
        self.lb_info.setStyleSheet(u"")
        self.lb_info.setFrameShape(QFrame.Box)
        self.lb_info.setFrameShadow(QFrame.Raised)
        self.lb_info.setLineWidth(1)
        self.lb_info.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.lb_info.setMargin(1)
        self.size_view = QLabel(self.frame_3)
        self.size_view.setObjectName(u"size_view")
        self.size_view.setGeometry(QRect(360, 450, 531, 421))
        self.size_view.setStyleSheet(u"background: transparent;")
        self.size_view.setFrameShape(QFrame.WinPanel)
        self.obj_view = QLabel(self.frame_3)
        self.obj_view.setObjectName(u"obj_view")
        self.obj_view.setGeometry(QRect(360, 20, 531, 421))
        self.obj_view.setStyleSheet(u"background: transparent;")
        self.obj_view.setFrameShape(QFrame.WinPanel)
        self.obj_view.setFrameShadow(QFrame.Plain)
        self.logo_view = QLabel(self.frame_3)
        self.logo_view.setObjectName(u"logo_view")
        self.logo_view.setGeometry(QRect(50, 680, 261, 191))
        self.logo_view.setStyleSheet(u"background: transparent;")
        self.logo_view.setFrameShape(QFrame.WinPanel)
        self.groupBox = QGroupBox(self.frame_3)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 20, 191, 311))
        self.groupBox.setFont(font4)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet(u"border: 2px solid #000000;")
        self.groupBox.setFlat(False)
        self.btn_run = QPushButton(self.groupBox)
        self.btn_run.setObjectName(u"btn_run")
        self.btn_run.setGeometry(QRect(10, 100, 171, 33))
        self.btn_run.setFont(font7)
        self.btn_run.setAutoDefault(True)
        self.btn_start = QPushButton(self.groupBox)
        self.btn_start.setObjectName(u"btn_start")
        self.btn_start.setGeometry(QRect(10, 40, 171, 51))
        font14 = QFont()
        font14.setPointSize(12)
        font14.setBold(False)
        font14.setWeight(50)
        self.btn_start.setFont(font14)
        self.btn_start.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_start.setFocusPolicy(Qt.StrongFocus)
        self.btn_start.setStyleSheet(u"background: #FFFFFF;border-color: rgb(0, 0, 0);border-width : 2px;\n"
"")
        icon2 = QIcon()
        icon2.addFile(u"GUI/icon_turn_on.PNG", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_start.setIcon(icon2)
        self.btn_start.setIconSize(QSize(40, 40))
        self.btn_start.setAutoDefault(True)
        self.btn_start.setFlat(False)
        self.btn_stop = QPushButton(self.groupBox)
        self.btn_stop.setObjectName(u"btn_stop")
        self.btn_stop.setGeometry(QRect(10, 140, 171, 33))
        self.btn_stop.setFont(font7)
        self.btn_stop.setAutoDefault(True)
        self.btn_reset = QPushButton(self.groupBox)
        self.btn_reset.setObjectName(u"btn_reset")
        self.btn_reset.setGeometry(QRect(10, 180, 171, 33))
        self.btn_reset.setFont(font7)
        self.btn_reset.setAutoDefault(True)
        self.light_stt_2 = QLabel(self.groupBox)
        self.light_stt_2.setObjectName(u"light_stt_2")
        self.light_stt_2.setGeometry(QRect(60, 230, 71, 71))
        self.light_stt_2.setStyleSheet(u"background: rgb(255,0,0); border-radius:35px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width : 1px;\n"
"border-style:inset;")
        self.groupBox_10 = QGroupBox(self.frame_3)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(210, 20, 131, 311))
        self.groupBox_10.setFont(font4)
        self.groupBox_10.setStyleSheet(u"border: 2px solid #000000;")
        self.groupBox_10.setFlat(False)
        self.btn_calib_size = QPushButton(self.groupBox_10)
        self.btn_calib_size.setObjectName(u"btn_calib_size")
        self.btn_calib_size.setGeometry(QRect(10, 140, 111, 33))
        self.btn_calib_size.setFont(font7)
        self.btn_calib_size.setAutoDefault(True)
        self.btn_test_size = QPushButton(self.groupBox_10)
        self.btn_test_size.setObjectName(u"btn_test_size")
        self.btn_test_size.setGeometry(QRect(10, 180, 111, 33))
        self.btn_test_size.setFont(font7)
        self.btn_test_size.setAutoDefault(True)
        self.btn_calib_mode = QPushButton(self.groupBox_10)
        self.btn_calib_mode.setObjectName(u"btn_calib_mode")
        self.btn_calib_mode.setGeometry(QRect(10, 40, 111, 71))
        self.btn_calib_mode.setFont(font7)
        self.btn_calib_mode.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_calib_mode.setStyleSheet(u"background: rgb(235,235,235)")
        self.btn_calib_mode.setAutoDefault(True)
        self.tabWidget.addTab(self.control_tab, "")
        self.tools_tab = QWidget()
        self.tools_tab.setObjectName(u"tools_tab")
        self.frame_8 = QFrame(self.tools_tab)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(10, 40, 341, 841))
        self.frame_8.setStyleSheet(u"")
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Plain)
        self.groupBox_11 = QGroupBox(self.frame_8)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(10, 270, 311, 151))
        self.groupBox_11.setFont(font4)
        self.cb_calib_model = QComboBox(self.groupBox_11)
        self.cb_calib_model.setObjectName(u"cb_calib_model")
        self.cb_calib_model.setGeometry(QRect(10, 60, 181, 31))
        self.cb_calib_model.setFont(font2)
        self.label_44 = QLabel(self.groupBox_11)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(10, 30, 55, 21))
        self.label_44.setFont(font7)
        self.label_44.setStyleSheet(u"background: transparent;")
        self.btn_apply_calib_model = QPushButton(self.groupBox_11)
        self.btn_apply_calib_model.setObjectName(u"btn_apply_calib_model")
        self.btn_apply_calib_model.setGeometry(QRect(200, 60, 101, 31))
        self.btn_apply_calib_model.setFont(font2)
        self.txt_calib_model = QLabel(self.groupBox_11)
        self.txt_calib_model.setObjectName(u"txt_calib_model")
        self.txt_calib_model.setGeometry(QRect(10, 110, 291, 31))
        font15 = QFont()
        font15.setFamily(u"Noto Sans")
        font15.setPointSize(8)
        font15.setBold(False)
        font15.setItalic(False)
        font15.setWeight(50)
        self.txt_calib_model.setFont(font15)
        self.txt_calib_model.setFrameShape(QFrame.WinPanel)
        self.txt_calib_model.setFrameShadow(QFrame.Raised)
        self.txt_calib_model.setAlignment(Qt.AlignCenter)
        self.groupBox_12 = QGroupBox(self.frame_8)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(10, 430, 311, 131))
        self.groupBox_12.setFont(font4)
        self.btn_on_cam_test = QPushButton(self.groupBox_12)
        self.btn_on_cam_test.setObjectName(u"btn_on_cam_test")
        self.btn_on_cam_test.setGeometry(QRect(10, 40, 91, 71))
        font16 = QFont()
        font16.setPointSize(14)
        font16.setBold(False)
        font16.setWeight(50)
        self.btn_on_cam_test.setFont(font16)
        self.btn_on_cam_test.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_on_cam_test.setStyleSheet(u"background: rgb(235,235,235)")
        self.btn_on_cam_test.setAutoDefault(True)
        self.slide_points_test = QSlider(self.groupBox_12)
        self.slide_points_test.setObjectName(u"slide_points_test")
        self.slide_points_test.setGeometry(QRect(120, 90, 171, 22))
        self.slide_points_test.setStyleSheet(u"background: transparent;")
        self.slide_points_test.setMinimum(5)
        self.slide_points_test.setMaximum(15)
        self.slide_points_test.setOrientation(Qt.Horizontal)
        self.label_39 = QLabel(self.groupBox_12)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(120, 45, 171, 31))
        self.label_39.setFont(font2)
        self.groupBox_9 = QGroupBox(self.frame_8)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(10, 110, 311, 151))
        self.groupBox_9.setFont(font4)
        self.groupBox_9.setStyleSheet(u"")
        self.btn_calib_mode_cam = QPushButton(self.groupBox_9)
        self.btn_calib_mode_cam.setObjectName(u"btn_calib_mode_cam")
        self.btn_calib_mode_cam.setGeometry(QRect(10, 30, 91, 71))
        self.btn_calib_mode_cam.setFont(font7)
        self.btn_calib_mode_cam.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_calib_mode_cam.setStyleSheet(u"background: rgb(235,235,235)")
        self.btn_calib_mode_cam.setAutoDefault(True)
        self.btn_scrshot = QPushButton(self.groupBox_9)
        self.btn_scrshot.setObjectName(u"btn_scrshot")
        self.btn_scrshot.setGeometry(QRect(10, 110, 91, 31))
        self.btn_scrshot.setFont(font2)
        self.btn_calib_cam = QPushButton(self.groupBox_9)
        self.btn_calib_cam.setObjectName(u"btn_calib_cam")
        self.btn_calib_cam.setGeometry(QRect(110, 110, 91, 31))
        self.btn_calib_cam.setFont(font2)
        self.btn_save_model = QPushButton(self.groupBox_9)
        self.btn_save_model.setObjectName(u"btn_save_model")
        self.btn_save_model.setGeometry(QRect(210, 110, 91, 31))
        self.btn_save_model.setFont(font2)
        self.label_47 = QLabel(self.groupBox_9)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(130, 30, 171, 21))
        font17 = QFont()
        font17.setFamily(u"Arial Narrow")
        font17.setPointSize(8)
        font17.setBold(True)
        font17.setItalic(False)
        font17.setWeight(75)
        self.label_47.setFont(font17)
        self.txt_name_calib_model = QTextEdit(self.groupBox_9)
        self.txt_name_calib_model.setObjectName(u"txt_name_calib_model")
        self.txt_name_calib_model.setGeometry(QRect(130, 60, 171, 31))
        self.txt_name_calib_model.setFont(font2)
        self.txt_name_calib_model.viewport().setProperty("cursor", QCursor(Qt.IBeamCursor))
        self.txt_name_calib_model.setStyleSheet(u"background: #FFFFFF")
        self.txt_name_calib_model.setFrameShape(QFrame.WinPanel)
        self.txt_name_calib_model.setFrameShadow(QFrame.Sunken)
        self.txt_name_calib_model.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_name_calib_model.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_name_calib_model.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.label_48 = QLabel(self.frame_8)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(20, 20, 91, 31))
        font18 = QFont()
        font18.setPointSize(10)
        font18.setBold(True)
        font18.setWeight(75)
        self.label_48.setFont(font18)
        self.label_48.setStyleSheet(u"background: transparent;")
        self.cb_opt_calib_cam = QComboBox(self.frame_8)
        self.cb_opt_calib_cam.setObjectName(u"cb_opt_calib_cam")
        self.cb_opt_calib_cam.setGeometry(QRect(120, 20, 201, 31))
        self.cb_opt_calib_cam.setStyleSheet(u"")
        self.lb_opt_calib_cam = QLabel(self.frame_8)
        self.lb_opt_calib_cam.setObjectName(u"lb_opt_calib_cam")
        self.lb_opt_calib_cam.setGeometry(QRect(120, 60, 201, 31))
        font19 = QFont()
        font19.setFamily(u"Noto Sans")
        font19.setItalic(False)
        self.lb_opt_calib_cam.setFont(font19)
        self.lb_opt_calib_cam.setFrameShape(QFrame.WinPanel)
        self.lb_opt_calib_cam.setFrameShadow(QFrame.Raised)
        self.label_16 = QLabel(self.frame_8)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 570, 311, 61))
        font20 = QFont()
        font20.setPointSize(10)
        font20.setBold(True)
        font20.setItalic(False)
        font20.setUnderline(False)
        font20.setWeight(75)
        self.label_16.setFont(font20)
        self.label_16.setStyleSheet(u"color: rgb(255,0,0);\n"
"")
        self.label_16.setFrameShape(QFrame.Box)
        self.label_16.setTextFormat(Qt.AutoText)
        self.label_16.setScaledContents(True)
        self.label_16.setAlignment(Qt.AlignCenter)
        self.label_16.setWordWrap(True)
        self.label_50 = QLabel(self.frame_8)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(40, 640, 251, 191))
        self.label_50.setPixmap(QPixmap(u"GUI/img_ex_checkerboard.png"))
        self.label_50.setScaledContents(True)
        self.frame = QFrame(self.tools_tab)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(350, 40, 811, 841))
        self.frame.setStyleSheet(u"")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Plain)
        self.gridLayoutWidget = QWidget(self.frame)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(50, 100, 711, 531))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.calib_cam_view = QLabel(self.gridLayoutWidget)
        self.calib_cam_view.setObjectName(u"calib_cam_view")
        self.calib_cam_view.setFrameShape(QFrame.WinPanel)

        self.gridLayout.addWidget(self.calib_cam_view, 0, 0, 1, 1)

        self.label_46 = QLabel(self.frame)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(50, 50, 711, 51))
        font21 = QFont()
        font21.setFamily(u"Barlow Condensed Light")
        font21.setPointSize(10)
        font21.setBold(True)
        font21.setWeight(75)
        self.label_46.setFont(font21)
        self.label_46.setAlignment(Qt.AlignCenter)
        self.txt_info_calib_cam = QLabel(self.frame)
        self.txt_info_calib_cam.setObjectName(u"txt_info_calib_cam")
        self.txt_info_calib_cam.setGeometry(QRect(50, 640, 711, 31))
        font22 = QFont()
        font22.setFamily(u"Noto Serif")
        font22.setPointSize(10)
        font22.setBold(True)
        font22.setWeight(75)
        self.txt_info_calib_cam.setFont(font22)
        self.txt_info_calib_cam.setStyleSheet(u"background: #FFFFFF")
        self.txt_info_calib_cam.setFrameShape(QFrame.WinPanel)
        self.txt_info_calib_cam.setFrameShadow(QFrame.Sunken)
        self.frame_4 = QFrame(self.tools_tab)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(10, 0, 1151, 41))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Plain)
        self.verticalLayoutWidget = QWidget(self.frame_4)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(-1, 0, 1151, 41))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_43 = QLabel(self.verticalLayoutWidget)
        self.label_43.setObjectName(u"label_43")
        font23 = QFont()
        font23.setPointSize(15)
        self.label_43.setFont(font23)
        self.label_43.setStyleSheet(u"border: 1px solid #000000;background-color:rgb(254, 20, 43);color: #000000;")
        self.label_43.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.label_43)

        self.frame_5 = QFrame(self.tools_tab)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(1160, 40, 641, 841))
        self.frame_5.setStyleSheet(u"")
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Plain)
        self.frame_6 = QFrame(self.tools_tab)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(1160, 0, 641, 41))
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Plain)
        self.tabWidget.addTab(self.tools_tab, "")
        self.widget = QWidget()
        self.widget.setObjectName(u"widget")
        self.tabWidget.addTab(self.widget, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.btn_start.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"RobotControlSoftware", None))
        self.groupBox_1.setTitle(QCoreApplication.translate("MainWindow", u"Port Connection", None))
        self.com_label.setText(QCoreApplication.translate("MainWindow", u"COM", None))
        self.baud_label.setText(QCoreApplication.translate("MainWindow", u"BAUDRATE", None))
        self.btn_cnt.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.light_stt.setText("")
        self.text_stt.setText(QCoreApplication.translate("MainWindow", u"Status: Off ", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"Calibrate Robot", None))
        self.btn_calibJ1.setText(QCoreApplication.translate("MainWindow", u"Calibrate Joint 1", None))
        self.btn_calibJ2.setText(QCoreApplication.translate("MainWindow", u"Calibrate Joint 2", None))
        self.btn_calibJ3.setText(QCoreApplication.translate("MainWindow", u"Calibrate Joint 3", None))
        self.btn_Home.setText(QCoreApplication.translate("MainWindow", u"Home", None))
        self.btn_calibHome.setText(QCoreApplication.translate("MainWindow", u"Home Calibration", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Moving Configuration ", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Incremental speed", None))
        self.btn_apply.setText(QCoreApplication.translate("MainWindow", u"Apply", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Incremental acceleration", None))
        self.light_stt_sp.setText("")
        self.light_stt_acc.setText("")
        self.light_stt_sp_2.setText("")
        self.light_stt_sp_3.setText("")
        self.light_stt_sp_4.setText("")
        self.light_stt_sp_5.setText("")
        self.light_stt_sp_6.setText("")
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Very slow", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Normal", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"Slow", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"Fast", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"Very fast", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Joint Mode", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Joint 1", None))
        self.btn_j1_dec.setText("")
        self.btn_j1_inc.setText("")
        self.btn_j2_inc.setText("")
        self.txt_j2.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Joint 2", None))
        self.btn_j2_dec.setText("")
        self.btn_j3_inc.setText("")
        self.txt_j3.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Joint 3", None))
        self.btn_j3_dec.setText("")
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Incremental distance", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"deg", None))
        self.txt_deg.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.txt_j1.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"World Mode", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.btn_x_dec.setText("")
        self.txt_x.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.btn_x_inc.setText("")
        self.btn_y_inc.setText("")
        self.txt_y.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.btn_y_dec.setText("")
        self.btn_z_inc.setText("")
        self.txt_z.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.btn_z_dec.setText("")
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"Incremental distance", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"cm", None))
        self.txt_cm.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Teaching Pendant", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Size type:", None))
        self.btn_savepoint.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.rbutton_new.setText(QCoreApplication.translate("MainWindow", u"create new point", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Point:", None))
        self.btn_reset_point.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"Current Position and Direction", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Roll", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Pitch", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Yaw", None))
        self.txt_cX.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"cm", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"cm", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"cm", None))
        self.txt_cZ.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.txt_cY.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"deg", None))
        self.txt_cRoll.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"deg", None))
        self.txt_cPitch.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"deg", None))
        self.txt_cYaw.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Moving Robot", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.txt_mY.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.txt_mX.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"cm", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.txt_mZ.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"cm", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"cm", None))
        self.btn_move.setText(QCoreApplication.translate("MainWindow", u"Move", None))
        self.groupBox_13.setTitle(QCoreApplication.translate("MainWindow", u"Vacuum", None))
        self.btn_end_effector.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Detection Results", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Size", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Color", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"Product result", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"Pick-place", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"Drop-place", None))
        self.res_size.setText(QCoreApplication.translate("MainWindow", u"not detect", None))
        self.res_color.setText(QCoreApplication.translate("MainWindow", u"not detect", None))
        self.result.setText(QCoreApplication.translate("MainWindow", u"not detect", None))
        self.pick_pl.setText(QCoreApplication.translate("MainWindow", u"not detect", None))
        self.drop_pl.setText(QCoreApplication.translate("MainWindow", u"not detect", None))
        self.lb_info.setText("")
        self.size_view.setText("")
        self.obj_view.setText("")
        self.logo_view.setText("")
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Auto Mode", None))
        self.btn_run.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.btn_start.setText(QCoreApplication.translate("MainWindow", u" Start Cam", None))
        self.btn_stop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.btn_reset.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.light_stt_2.setText("")
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"Size Calibration", None))
        self.btn_calib_size.setText(QCoreApplication.translate("MainWindow", u"Calibrate", None))
        self.btn_test_size.setText(QCoreApplication.translate("MainWindow", u"Test", None))
        self.btn_calib_mode.setText(QCoreApplication.translate("MainWindow", u"On Mode", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.control_tab), QCoreApplication.translate("MainWindow", u"Robot Control", None))
        self.groupBox_11.setTitle(QCoreApplication.translate("MainWindow", u"Pretrained Calib Model", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"Model:", None))
        self.btn_apply_calib_model.setText(QCoreApplication.translate("MainWindow", u"Apply", None))
        self.txt_calib_model.setText(QCoreApplication.translate("MainWindow", u"Level 2 model defaults", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("MainWindow", u"Test Model", None))
        self.btn_on_cam_test.setText(QCoreApplication.translate("MainWindow", u"ON", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"Inc/Dec points", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"Customize New Model", None))
        self.btn_calib_mode_cam.setText(QCoreApplication.translate("MainWindow", u"On Mode", None))
        self.btn_scrshot.setText(QCoreApplication.translate("MainWindow", u"ScreenShot", None))
        self.btn_calib_cam.setText(QCoreApplication.translate("MainWindow", u"Calibrate", None))
        self.btn_save_model.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"Insert name of new model:", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"OPTION", None))
        self.lb_opt_calib_cam.setText(QCoreApplication.translate("MainWindow", u"Use pretrained model", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Insert the checkerboard (8x6) to\n"
"calibrate the camera", None))
        self.label_50.setText("")
        self.calib_cam_view.setText("")
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"Calibration View", None))
        self.txt_info_calib_cam.setText("")
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"CAMERA CALIBRATION", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tools_tab), QCoreApplication.translate("MainWindow", u"Tools", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), "")
    # retranslateUi

