# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(912, 938)
        MainWindow.setWindowOpacity(1.000000000000000)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 921, 921))
        self.manual_tab = QWidget()
        self.manual_tab.setObjectName(u"manual_tab")
        self.frame1 = QFrame(self.manual_tab)
        self.frame1.setObjectName(u"frame1")
        self.frame1.setGeometry(QRect(0, 0, 901, 301))
        self.frame1.setFrameShape(QFrame.StyledPanel)
        self.frame1.setFrameShadow(QFrame.Plain)
        self.groupBox_1 = QGroupBox(self.frame1)
        self.groupBox_1.setObjectName(u"groupBox_1")
        self.groupBox_1.setGeometry(QRect(10, 20, 191, 271))
        font = QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox_1.setFont(font)
        self.com_label = QLabel(self.groupBox_1)
        self.com_label.setObjectName(u"com_label")
        self.com_label.setGeometry(QRect(10, 30, 55, 31))
        font1 = QFont()
        font1.setBold(False)
        font1.setUnderline(False)
        font1.setWeight(50)
        self.com_label.setFont(font1)
        self.com_label.setLayoutDirection(Qt.LeftToRight)
        self.baud_label = QLabel(self.groupBox_1)
        self.baud_label.setObjectName(u"baud_label")
        self.baud_label.setGeometry(QRect(10, 75, 81, 21))
        self.baud_label.setFont(font1)
        self.btn_cnt = QPushButton(self.groupBox_1)
        self.btn_cnt.setObjectName(u"btn_cnt")
        self.btn_cnt.setGeometry(QRect(40, 120, 101, 41))
        font2 = QFont()
        font2.setPointSize(9)
        font2.setBold(False)
        font2.setUnderline(False)
        font2.setWeight(50)
        self.btn_cnt.setFont(font2)
        self.btn_cnt.setStyleSheet(u"")
        self.cb_com = QComboBox(self.groupBox_1)
        self.cb_com.setObjectName(u"cb_com")
        self.cb_com.setGeometry(QRect(90, 30, 91, 31))
        font3 = QFont()
        font3.setBold(False)
        font3.setWeight(50)
        self.cb_com.setFont(font3)
        self.cb_baudrate = QComboBox(self.groupBox_1)
        self.cb_baudrate.setObjectName(u"cb_baudrate")
        self.cb_baudrate.setGeometry(QRect(90, 70, 91, 31))
        self.cb_baudrate.setFont(font3)
        self.light_stt = QLabel(self.groupBox_1)
        self.light_stt.setObjectName(u"light_stt")
        self.light_stt.setGeometry(QRect(20, 190, 41, 41))
        self.light_stt.setStyleSheet(u"background: rgb(255,0,0); border-radius:20px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width : 0.5px;\n"
"border-style:inset;")
        self.text_stt = QLabel(self.groupBox_1)
        self.text_stt.setObjectName(u"text_stt")
        self.text_stt.setGeometry(QRect(60, 200, 121, 20))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setBold(False)
        font4.setUnderline(False)
        font4.setWeight(50)
        self.text_stt.setFont(font4)
        self.text_stt.setAlignment(Qt.AlignCenter)
        self.groupBox_7 = QGroupBox(self.frame1)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setEnabled(True)
        self.groupBox_7.setGeometry(QRect(220, 20, 221, 271))
        font5 = QFont()
        font5.setPointSize(9)
        font5.setBold(True)
        font5.setWeight(75)
        self.groupBox_7.setFont(font5)
        self.btn_calibJ1 = QPushButton(self.groupBox_7)
        self.btn_calibJ1.setObjectName(u"btn_calibJ1")
        self.btn_calibJ1.setGeometry(QRect(40, 30, 151, 31))
        font6 = QFont()
        font6.setPointSize(9)
        font6.setBold(False)
        font6.setWeight(50)
        self.btn_calibJ1.setFont(font6)
        self.btn_calibJ1.setAutoDefault(True)
        self.btn_calibJ2 = QPushButton(self.groupBox_7)
        self.btn_calibJ2.setObjectName(u"btn_calibJ2")
        self.btn_calibJ2.setGeometry(QRect(40, 80, 151, 31))
        self.btn_calibJ2.setFont(font6)
        self.btn_calibJ2.setAutoDefault(True)
        self.btn_calibJ3 = QPushButton(self.groupBox_7)
        self.btn_calibJ3.setObjectName(u"btn_calibJ3")
        self.btn_calibJ3.setGeometry(QRect(40, 130, 151, 31))
        self.btn_calibJ3.setFont(font6)
        self.btn_calibJ3.setAutoDefault(True)
        self.btn_Home = QPushButton(self.groupBox_7)
        self.btn_Home.setObjectName(u"btn_Home")
        self.btn_Home.setGeometry(QRect(40, 180, 151, 31))
        self.btn_Home.setFont(font6)
        self.btn_Home.setAutoDefault(True)
        self.btn_calibHome = QPushButton(self.groupBox_7)
        self.btn_calibHome.setObjectName(u"btn_calibHome")
        self.btn_calibHome.setGeometry(QRect(40, 230, 151, 31))
        self.btn_calibHome.setFont(font6)
        self.btn_calibHome.setAutoDefault(True)
        self.groupBox_6 = QGroupBox(self.frame1)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(460, 20, 431, 271))
        self.groupBox_6.setFont(font5)
        self.label_15 = QLabel(self.groupBox_6)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 40, 131, 16))
        self.label_15.setFont(font6)
        self.slide_speed = QSlider(self.groupBox_6)
        self.slide_speed.setObjectName(u"slide_speed")
        self.slide_speed.setGeometry(QRect(20, 70, 211, 22))
        self.slide_speed.setMaximum(40000)
        self.slide_speed.setSingleStep(2000)
        self.slide_speed.setSliderPosition(0)
        self.slide_speed.setOrientation(Qt.Horizontal)
        self.slide_speed.setTickPosition(QSlider.TicksBelow)
        self.slide_speed.setTickInterval(2000)
        self.label_33 = QLabel(self.groupBox_6)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(320, 60, 81, 31))
        font7 = QFont()
        font7.setPointSize(8)
        font7.setBold(False)
        font7.setWeight(50)
        self.label_33.setFont(font7)
        self.btn_apply = QPushButton(self.groupBox_6)
        self.btn_apply.setObjectName(u"btn_apply")
        self.btn_apply.setGeometry(QRect(110, 197, 151, 41))
        self.btn_apply.setFont(font6)
        self.btn_apply.setIconSize(QSize(20, 20))
        self.btn_apply.setAutoDefault(True)
        self.label_35 = QLabel(self.groupBox_6)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(20, 110, 171, 16))
        self.label_35.setFont(font6)
        self.txt_acc = QTextEdit(self.groupBox_6)
        self.txt_acc.setObjectName(u"txt_acc")
        self.txt_acc.setGeometry(QRect(240, 130, 71, 28))
        self.txt_acc.setFont(font6)
        self.txt_acc.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_acc.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_acc.setReadOnly(True)
        self.slide_acc = QSlider(self.groupBox_6)
        self.slide_acc.setObjectName(u"slide_acc")
        self.slide_acc.setGeometry(QRect(20, 140, 211, 22))
        self.slide_acc.setMaximum(40000)
        self.slide_acc.setSingleStep(2000)
        self.slide_acc.setOrientation(Qt.Horizontal)
        self.slide_acc.setTickPosition(QSlider.TicksBelow)
        self.slide_acc.setTickInterval(2000)
        self.label_36 = QLabel(self.groupBox_6)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(320, 130, 91, 31))
        self.label_36.setFont(font7)
        self.txt_speed = QTextEdit(self.groupBox_6)
        self.txt_speed.setObjectName(u"txt_speed")
        self.txt_speed.setGeometry(QRect(240, 60, 71, 28))
        self.txt_speed.setFont(font6)
        self.txt_speed.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_speed.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_speed.setReadOnly(True)
        self.frame_2 = QFrame(self.manual_tab)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(0, 300, 901, 581))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Plain)
        self.groupBox_5 = QGroupBox(self.frame_2)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 10, 431, 251))
        self.groupBox_5.setFont(font5)
        self.label = QLabel(self.groupBox_5)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 100, 70, 30))
        self.label.setFont(font6)
        self.label.setAlignment(Qt.AlignCenter)
        self.btn_j1_dec = QPushButton(self.groupBox_5)
        self.btn_j1_dec.setObjectName(u"btn_j1_dec")
        self.btn_j1_dec.setGeometry(QRect(90, 100, 100, 30))
        icon = QIcon()
        icon.addFile(u"phai.PNG", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_j1_dec.setIcon(icon)
        self.btn_j1_dec.setIconSize(QSize(20, 20))
        self.btn_j1_inc = QPushButton(self.groupBox_5)
        self.btn_j1_inc.setObjectName(u"btn_j1_inc")
        self.btn_j1_inc.setGeometry(QRect(310, 100, 100, 30))
        icon1 = QIcon()
        icon1.addFile(u"trai.PNG", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_j1_inc.setIcon(icon1)
        self.btn_j1_inc.setIconSize(QSize(20, 20))
        self.btn_j2_inc = QPushButton(self.groupBox_5)
        self.btn_j2_inc.setObjectName(u"btn_j2_inc")
        self.btn_j2_inc.setGeometry(QRect(310, 150, 100, 30))
        self.btn_j2_inc.setIcon(icon1)
        self.btn_j2_inc.setIconSize(QSize(20, 20))
        self.txt_j2 = QTextEdit(self.groupBox_5)
        self.txt_j2.setObjectName(u"txt_j2")
        self.txt_j2.setGeometry(QRect(200, 150, 100, 30))
        self.txt_j2.setFont(font6)
        self.txt_j2.setReadOnly(True)
        self.label_2 = QLabel(self.groupBox_5)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 150, 70, 30))
        self.label_2.setFont(font6)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.btn_j2_dec = QPushButton(self.groupBox_5)
        self.btn_j2_dec.setObjectName(u"btn_j2_dec")
        self.btn_j2_dec.setGeometry(QRect(90, 150, 100, 30))
        self.btn_j2_dec.setIcon(icon)
        self.btn_j2_dec.setIconSize(QSize(20, 20))
        self.btn_j3_inc = QPushButton(self.groupBox_5)
        self.btn_j3_inc.setObjectName(u"btn_j3_inc")
        self.btn_j3_inc.setGeometry(QRect(310, 200, 100, 30))
        self.btn_j3_inc.setIcon(icon1)
        self.btn_j3_inc.setIconSize(QSize(20, 20))
        self.txt_j3 = QTextEdit(self.groupBox_5)
        self.txt_j3.setObjectName(u"txt_j3")
        self.txt_j3.setGeometry(QRect(200, 200, 100, 30))
        self.txt_j3.setFont(font6)
        self.txt_j3.setReadOnly(True)
        self.label_3 = QLabel(self.groupBox_5)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 200, 70, 30))
        self.label_3.setFont(font6)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.btn_j3_dec = QPushButton(self.groupBox_5)
        self.btn_j3_dec.setObjectName(u"btn_j3_dec")
        self.btn_j3_dec.setGeometry(QRect(90, 200, 100, 30))
        self.btn_j3_dec.setIcon(icon)
        self.btn_j3_dec.setIconSize(QSize(20, 20))
        self.label_28 = QLabel(self.groupBox_5)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(140, 20, 141, 16))
        self.label_28.setFont(font6)
        self.slide_deg = QSlider(self.groupBox_5)
        self.slide_deg.setObjectName(u"slide_deg")
        self.slide_deg.setGeometry(QRect(110, 60, 191, 22))
        self.slide_deg.setFont(font6)
        self.slide_deg.setMaximum(20)
        self.slide_deg.setSingleStep(5)
        self.slide_deg.setOrientation(Qt.Horizontal)
        self.slide_deg.setTickPosition(QSlider.TicksBelow)
        self.slide_deg.setTickInterval(5)
        self.label_30 = QLabel(self.groupBox_5)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(370, 50, 31, 31))
        self.label_30.setFont(font6)
        self.txt_deg = QTextEdit(self.groupBox_5)
        self.txt_deg.setObjectName(u"txt_deg")
        self.txt_deg.setGeometry(QRect(310, 50, 51, 28))
        self.txt_deg.setFont(font6)
        self.txt_deg.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_deg.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_deg.setReadOnly(True)
        self.txt_j1 = QTextEdit(self.groupBox_5)
        self.txt_j1.setObjectName(u"txt_j1")
        self.txt_j1.setGeometry(QRect(200, 100, 101, 28))
        self.txt_j1.setFont(font6)
        self.txt_j1.setReadOnly(True)
        self.groupBox_3 = QGroupBox(self.frame_2)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(460, 10, 431, 251))
        self.groupBox_3.setFont(font5)
        self.label_4 = QLabel(self.groupBox_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 100, 70, 30))
        self.label_4.setFont(font6)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.btn_x_dec = QPushButton(self.groupBox_3)
        self.btn_x_dec.setObjectName(u"btn_x_dec")
        self.btn_x_dec.setGeometry(QRect(80, 100, 100, 30))
        self.btn_x_dec.setIcon(icon)
        self.btn_x_dec.setIconSize(QSize(20, 20))
        self.txt_x = QTextEdit(self.groupBox_3)
        self.txt_x.setObjectName(u"txt_x")
        self.txt_x.setGeometry(QRect(190, 100, 100, 30))
        self.txt_x.setFont(font6)
        self.txt_x.setReadOnly(True)
        self.btn_x_inc = QPushButton(self.groupBox_3)
        self.btn_x_inc.setObjectName(u"btn_x_inc")
        self.btn_x_inc.setGeometry(QRect(300, 100, 100, 30))
        self.btn_x_inc.setIcon(icon1)
        self.btn_x_inc.setIconSize(QSize(20, 20))
        self.btn_y_inc = QPushButton(self.groupBox_3)
        self.btn_y_inc.setObjectName(u"btn_y_inc")
        self.btn_y_inc.setGeometry(QRect(300, 150, 100, 30))
        self.btn_y_inc.setIcon(icon1)
        self.btn_y_inc.setIconSize(QSize(20, 20))
        self.txt_y = QTextEdit(self.groupBox_3)
        self.txt_y.setObjectName(u"txt_y")
        self.txt_y.setGeometry(QRect(190, 150, 100, 30))
        self.txt_y.setFont(font6)
        self.txt_y.setReadOnly(True)
        self.label_5 = QLabel(self.groupBox_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 150, 70, 30))
        self.label_5.setFont(font6)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.btn_y_dec = QPushButton(self.groupBox_3)
        self.btn_y_dec.setObjectName(u"btn_y_dec")
        self.btn_y_dec.setGeometry(QRect(80, 150, 100, 30))
        self.btn_y_dec.setIcon(icon)
        self.btn_y_dec.setIconSize(QSize(20, 20))
        self.btn_z_inc = QPushButton(self.groupBox_3)
        self.btn_z_inc.setObjectName(u"btn_z_inc")
        self.btn_z_inc.setGeometry(QRect(300, 200, 100, 30))
        self.btn_z_inc.setIcon(icon1)
        self.btn_z_inc.setIconSize(QSize(20, 20))
        self.txt_z = QTextEdit(self.groupBox_3)
        self.txt_z.setObjectName(u"txt_z")
        self.txt_z.setGeometry(QRect(190, 200, 100, 30))
        self.txt_z.setFont(font6)
        self.txt_z.setReadOnly(True)
        self.label_6 = QLabel(self.groupBox_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 200, 70, 30))
        self.label_6.setFont(font6)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.btn_z_dec = QPushButton(self.groupBox_3)
        self.btn_z_dec.setObjectName(u"btn_z_dec")
        self.btn_z_dec.setGeometry(QRect(80, 200, 100, 30))
        self.btn_z_dec.setIcon(icon)
        self.btn_z_dec.setIconSize(QSize(20, 20))
        self.label_37 = QLabel(self.groupBox_3)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(130, 20, 141, 16))
        self.label_37.setFont(font6)
        self.label_29 = QLabel(self.groupBox_3)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(360, 50, 31, 31))
        self.label_29.setFont(font6)
        self.slide_cm = QSlider(self.groupBox_3)
        self.slide_cm.setObjectName(u"slide_cm")
        self.slide_cm.setGeometry(QRect(100, 60, 191, 22))
        self.slide_cm.setFont(font6)
        self.slide_cm.setMaximum(5)
        self.slide_cm.setOrientation(Qt.Horizontal)
        self.slide_cm.setTickPosition(QSlider.TicksBelow)
        self.slide_cm.setTickInterval(1)
        self.txt_cm = QTextEdit(self.groupBox_3)
        self.txt_cm.setObjectName(u"txt_cm")
        self.txt_cm.setGeometry(QRect(300, 50, 51, 28))
        self.txt_cm.setFont(font6)
        self.txt_cm.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_cm.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_cm.setReadOnly(True)
        self.groupBox_4 = QGroupBox(self.frame_2)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 270, 381, 301))
        self.groupBox_4.setFont(font5)
        self.groupBox_8 = QGroupBox(self.frame_2)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(400, 270, 251, 301))
        self.groupBox_8.setFont(font5)
        self.label_8 = QLabel(self.groupBox_8)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(40, 35, 41, 21))
        self.label_8.setFont(font6)
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(self.groupBox_8)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(40, 80, 41, 21))
        self.label_9.setFont(font6)
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_10 = QLabel(self.groupBox_8)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(40, 125, 41, 21))
        self.label_10.setFont(font6)
        self.label_10.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(self.groupBox_8)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(40, 170, 41, 21))
        self.label_11.setFont(font6)
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_12 = QLabel(self.groupBox_8)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(40, 210, 41, 31))
        self.label_12.setFont(font6)
        self.label_12.setAlignment(Qt.AlignCenter)
        self.label_13 = QLabel(self.groupBox_8)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(40, 260, 41, 21))
        self.label_13.setFont(font6)
        self.label_13.setAlignment(Qt.AlignCenter)
        self.txt_cX = QTextEdit(self.groupBox_8)
        self.txt_cX.setObjectName(u"txt_cX")
        self.txt_cX.setGeometry(QRect(80, 30, 81, 31))
        self.txt_cX.setFont(font6)
        self.txt_cX.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_cX.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_cX.setReadOnly(True)
        self.label_14 = QLabel(self.groupBox_8)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(160, 30, 41, 31))
        self.label_14.setFont(font6)
        self.label_14.setAlignment(Qt.AlignCenter)
        self.label_22 = QLabel(self.groupBox_8)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(160, 80, 41, 21))
        self.label_22.setFont(font6)
        self.label_22.setAlignment(Qt.AlignCenter)
        self.label_23 = QLabel(self.groupBox_8)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(160, 125, 41, 21))
        self.label_23.setFont(font6)
        self.label_23.setAlignment(Qt.AlignCenter)
        self.txt_cZ = QTextEdit(self.groupBox_8)
        self.txt_cZ.setObjectName(u"txt_cZ")
        self.txt_cZ.setGeometry(QRect(80, 120, 81, 31))
        self.txt_cZ.setFont(font6)
        self.txt_cZ.setReadOnly(True)
        self.txt_cY = QTextEdit(self.groupBox_8)
        self.txt_cY.setObjectName(u"txt_cY")
        self.txt_cY.setGeometry(QRect(80, 75, 81, 31))
        self.txt_cY.setFont(font6)
        self.txt_cY.setReadOnly(True)
        self.label_24 = QLabel(self.groupBox_8)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(160, 160, 41, 31))
        self.label_24.setFont(font6)
        self.label_24.setAlignment(Qt.AlignCenter)
        self.txt_cRoll = QTextEdit(self.groupBox_8)
        self.txt_cRoll.setObjectName(u"txt_cRoll")
        self.txt_cRoll.setGeometry(QRect(80, 165, 81, 31))
        self.txt_cRoll.setFont(font6)
        self.txt_cRoll.setReadOnly(True)
        self.label_25 = QLabel(self.groupBox_8)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(160, 210, 41, 31))
        self.label_25.setFont(font6)
        self.label_25.setAlignment(Qt.AlignCenter)
        self.txt_cPitch = QTextEdit(self.groupBox_8)
        self.txt_cPitch.setObjectName(u"txt_cPitch")
        self.txt_cPitch.setGeometry(QRect(80, 210, 81, 31))
        self.txt_cPitch.setFont(font6)
        self.txt_cPitch.setReadOnly(True)
        self.label_26 = QLabel(self.groupBox_8)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(160, 250, 41, 31))
        self.label_26.setFont(font6)
        self.label_26.setAlignment(Qt.AlignCenter)
        self.txt_cYaw = QTextEdit(self.groupBox_8)
        self.txt_cYaw.setObjectName(u"txt_cYaw")
        self.txt_cYaw.setGeometry(QRect(80, 255, 81, 31))
        self.txt_cYaw.setFont(font6)
        self.txt_cYaw.setReadOnly(True)
        self.groupBox_2 = QGroupBox(self.frame_2)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(660, 270, 231, 301))
        self.groupBox_2.setFont(font5)
        self.label_17 = QLabel(self.groupBox_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(40, 80, 41, 21))
        self.label_17.setFont(font6)
        self.label_17.setAlignment(Qt.AlignCenter)
        self.txt_mY = QTextEdit(self.groupBox_2)
        self.txt_mY.setObjectName(u"txt_mY")
        self.txt_mY.setGeometry(QRect(80, 75, 81, 31))
        self.txt_mY.setFont(font6)
        self.txt_mY.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_mY.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_mX = QTextEdit(self.groupBox_2)
        self.txt_mX.setObjectName(u"txt_mX")
        self.txt_mX.setGeometry(QRect(80, 30, 81, 31))
        self.txt_mX.setFont(font6)
        self.txt_mX.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_mX.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.label_27 = QLabel(self.groupBox_2)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(160, 80, 41, 21))
        self.label_27.setFont(font6)
        self.label_27.setAlignment(Qt.AlignCenter)
        self.label_18 = QLabel(self.groupBox_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(40, 35, 41, 21))
        self.label_18.setFont(font6)
        self.label_18.setAlignment(Qt.AlignCenter)
        self.txt_mZ = QTextEdit(self.groupBox_2)
        self.txt_mZ.setObjectName(u"txt_mZ")
        self.txt_mZ.setGeometry(QRect(80, 120, 81, 31))
        self.txt_mZ.setFont(font6)
        self.txt_mZ.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_mZ.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.label_19 = QLabel(self.groupBox_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(160, 35, 41, 21))
        self.label_19.setFont(font6)
        self.label_19.setAlignment(Qt.AlignCenter)
        self.label_20 = QLabel(self.groupBox_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(40, 125, 41, 21))
        self.label_20.setFont(font6)
        self.label_20.setAlignment(Qt.AlignCenter)
        self.label_38 = QLabel(self.groupBox_2)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(160, 125, 41, 21))
        self.label_38.setFont(font6)
        self.label_38.setAlignment(Qt.AlignCenter)
        self.btn_move = QPushButton(self.groupBox_2)
        self.btn_move.setObjectName(u"btn_move")
        self.btn_move.setGeometry(QRect(70, 179, 100, 41))
        self.btn_move.setFont(font3)
        self.btn_move.setIconSize(QSize(20, 20))
        self.btn_move.setAutoDefault(True)
        self.tabWidget.addTab(self.manual_tab, "")
        self.auto_tab = QWidget()
        self.auto_tab.setObjectName(u"auto_tab")
        self.frame = QFrame(self.auto_tab)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 0, 901, 131))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Plain)
        self.btn_start = QPushButton(self.frame)
        self.btn_start.setObjectName(u"btn_start")
        self.btn_start.setGeometry(QRect(20, 20, 191, 49))
        font8 = QFont()
        font8.setPointSize(12)
        self.btn_start.setFont(font8)
        self.btn_start.setFocusPolicy(Qt.StrongFocus)
        self.btn_start.setStyleSheet(u"background: #FFFFFF;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width : 0.5px;\n"
"border-style:inset;\n"
"")
        icon2 = QIcon()
        icon2.addFile(u"turn_on.PNG", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_start.setIcon(icon2)
        self.btn_start.setIconSize(QSize(40, 40))
        self.btn_start.setAutoDefault(True)
        self.btn_start.setFlat(False)
        self.btn_run = QPushButton(self.frame)
        self.btn_run.setObjectName(u"btn_run")
        self.btn_run.setGeometry(QRect(530, 10, 161, 33))
        self.btn_run.setFont(font8)
        self.btn_run.setAutoDefault(True)
        self.btn_close = QPushButton(self.frame)
        self.btn_close.setObjectName(u"btn_close")
        self.btn_close.setGeometry(QRect(530, 50, 161, 33))
        self.btn_close.setFont(font8)
        self.btn_close.setAutoDefault(True)
        self.btn_reset = QPushButton(self.frame)
        self.btn_reset.setObjectName(u"btn_reset")
        self.btn_reset.setGeometry(QRect(530, 90, 161, 33))
        self.btn_reset.setFont(font8)
        self.btn_reset.setAutoDefault(True)
        self.light_stt_2 = QLabel(self.frame)
        self.light_stt_2.setObjectName(u"light_stt_2")
        self.light_stt_2.setGeometry(QRect(710, 30, 71, 71))
        self.light_stt_2.setStyleSheet(u"background: rgb(255,0,0); border-radius:35px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width : 1px;\n"
"border-style:inset;")
        self.text_stt_2 = QLabel(self.frame)
        self.text_stt_2.setObjectName(u"text_stt_2")
        self.text_stt_2.setGeometry(QRect(780, 50, 111, 31))
        self.text_stt_2.setFont(font4)
        self.text_stt_2.setAlignment(Qt.AlignCenter)
        self.groupBox = QGroupBox(self.frame)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(230, 10, 241, 111))
        self.groupBox.setFont(font5)
        self.btn_calib_size = QPushButton(self.groupBox)
        self.btn_calib_size.setObjectName(u"btn_calib_size")
        self.btn_calib_size.setGeometry(QRect(130, 30, 101, 33))
        font9 = QFont()
        font9.setPointSize(10)
        font9.setBold(False)
        font9.setWeight(50)
        self.btn_calib_size.setFont(font9)
        self.btn_calib_size.setAutoDefault(True)
        self.btn_test_size = QPushButton(self.groupBox)
        self.btn_test_size.setObjectName(u"btn_test_size")
        self.btn_test_size.setGeometry(QRect(130, 70, 101, 33))
        self.btn_test_size.setFont(font9)
        self.btn_test_size.setAutoDefault(True)
        self.btn_calib_mode = QPushButton(self.groupBox)
        self.btn_calib_mode.setObjectName(u"btn_calib_mode")
        self.btn_calib_mode.setGeometry(QRect(10, 30, 101, 33))
        self.btn_calib_mode.setFont(font9)
        self.btn_calib_mode.setAutoDefault(True)
        self.frame_3 = QFrame(self.auto_tab)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(0, 130, 901, 751))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Plain)
        self.verticalLayoutWidget = QWidget(self.frame_3)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(10, 10, 521, 361))
        self.obj_layout = QVBoxLayout(self.verticalLayoutWidget)
        self.obj_layout.setObjectName(u"obj_layout")
        self.obj_layout.setContentsMargins(0, 0, 0, 0)
        self.frame_4 = QFrame(self.verticalLayoutWidget)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.obj_view = QLabel(self.frame_4)
        self.obj_view.setObjectName(u"obj_view")
        self.obj_view.setGeometry(QRect(10, 10, 501, 341))
        self.obj_view.setFrameShape(QFrame.WinPanel)
        self.obj_view.setFrameShadow(QFrame.Plain)

        self.obj_layout.addWidget(self.frame_4)

        self.verticalLayoutWidget_2 = QWidget(self.frame_3)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(10, 370, 521, 361))
        self.size_layout = QVBoxLayout(self.verticalLayoutWidget_2)
        self.size_layout.setObjectName(u"size_layout")
        self.size_layout.setContentsMargins(0, 0, 0, 0)
        self.frame_5 = QFrame(self.verticalLayoutWidget_2)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.size_view = QLabel(self.frame_5)
        self.size_view.setObjectName(u"size_view")
        self.size_view.setGeometry(QRect(10, 10, 501, 341))
        self.size_view.setFrameShape(QFrame.WinPanel)

        self.size_layout.addWidget(self.frame_5)

        self.verticalLayoutWidget_3 = QWidget(self.frame_3)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(570, 40, 301, 281))
        self.logo_layout = QVBoxLayout(self.verticalLayoutWidget_3)
        self.logo_layout.setObjectName(u"logo_layout")
        self.logo_layout.setContentsMargins(0, 0, 0, 0)
        self.frame_6 = QFrame(self.verticalLayoutWidget_3)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.logo_view = QLabel(self.frame_6)
        self.logo_view.setObjectName(u"logo_view")
        self.logo_view.setGeometry(QRect(4, 5, 291, 271))
        self.logo_view.setFrameShape(QFrame.WinPanel)

        self.logo_layout.addWidget(self.frame_6)

        self.frame_7 = QFrame(self.frame_3)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(580, 400, 281, 301))
        self.frame_7.setFrameShape(QFrame.WinPanel)
        self.frame_7.setFrameShadow(QFrame.Plain)
        self.tabWidget.addTab(self.auto_tab, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)
        self.btn_start.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"RobotControlSoftware", None))
        self.groupBox_1.setTitle(QCoreApplication.translate("MainWindow", u"Port Connection", None))
        self.com_label.setText(QCoreApplication.translate("MainWindow", u"COM", None))
        self.baud_label.setText(QCoreApplication.translate("MainWindow", u"BAUDRATE", None))
        self.btn_cnt.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.light_stt.setText("")
        self.text_stt.setText(QCoreApplication.translate("MainWindow", u"Status: Off ", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"Calibrate Robot", None))
        self.btn_calibJ1.setText(QCoreApplication.translate("MainWindow", u"Calibrate Joint 1", None))
        self.btn_calibJ2.setText(QCoreApplication.translate("MainWindow", u"Calibrate Joint 2", None))
        self.btn_calibJ3.setText(QCoreApplication.translate("MainWindow", u"Calibrate Joint 3", None))
        self.btn_Home.setText(QCoreApplication.translate("MainWindow", u"Home", None))
        self.btn_calibHome.setText(QCoreApplication.translate("MainWindow", u"Home Calibration", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Moving Configuration ", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Incremental speed", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"0.1125 deg/s", None))
        self.btn_apply.setText(QCoreApplication.translate("MainWindow", u"Apply", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Incremental acceleration", None))
        self.txt_acc.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"0.1125 deg/s^2", None))
        self.txt_speed.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Joint Mode", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Joint 1", None))
        self.btn_j1_dec.setText("")
        self.btn_j1_inc.setText("")
        self.btn_j2_inc.setText("")
        self.txt_j2.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Joint 2", None))
        self.btn_j2_dec.setText("")
        self.btn_j3_inc.setText("")
        self.txt_j3.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Joint 3", None))
        self.btn_j3_dec.setText("")
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Incremental distance", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"deg", None))
        self.txt_deg.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.txt_j1.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"World Mode", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.btn_x_dec.setText("")
        self.txt_x.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.btn_x_inc.setText("")
        self.btn_y_inc.setText("")
        self.txt_y.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.btn_y_dec.setText("")
        self.btn_z_inc.setText("")
        self.txt_z.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.btn_z_dec.setText("")
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"Incremental distance", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"cm", None))
        self.txt_cm.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Teaching Pendant", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"Current Position and Direction", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Roll", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Pitch", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Yaw", None))
        self.txt_cX.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"cm", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"cm", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"cm", None))
        self.txt_cZ.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.txt_cY.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"deg", None))
        self.txt_cRoll.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"deg", None))
        self.txt_cPitch.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"deg", None))
        self.txt_cYaw.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Moving Robot", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.txt_mY.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.txt_mX.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"cm", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.txt_mZ.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"cm", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"cm", None))
        self.btn_move.setText(QCoreApplication.translate("MainWindow", u"Move", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.manual_tab), QCoreApplication.translate("MainWindow", u"Manual", None))
        self.btn_start.setText(QCoreApplication.translate("MainWindow", u" Start Cam", None))
        self.btn_run.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.btn_close.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.btn_reset.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.light_stt_2.setText("")
        self.text_stt_2.setText(QCoreApplication.translate("MainWindow", u"Status: Off ", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Size Calibration", None))
        self.btn_calib_size.setText(QCoreApplication.translate("MainWindow", u"Calib Size", None))
        self.btn_test_size.setText(QCoreApplication.translate("MainWindow", u"Test Size", None))
        self.btn_calib_mode.setText(QCoreApplication.translate("MainWindow", u"On Mode", None))
        self.obj_view.setText("")
        self.size_view.setText("")
        self.logo_view.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.auto_tab), QCoreApplication.translate("MainWindow", u"Auto", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Management", None))
    # retranslateUi

