# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui_size.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(813, 447)
        icon = QIcon()
        icon.addFile(u"GUI/icon_tools.png", QSize(), QIcon.Normal, QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(193, 187, 181, 255), stop:1 rgba(255, 255, 255, 255))")
        self.groupBox_10 = QGroupBox(Dialog)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(10, 10, 251, 131))
        font = QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setStyleSheet(u"border: 2px solid #000000;")
        self.groupBox_10.setFlat(False)
        self.btn_calib_size = QPushButton(self.groupBox_10)
        self.btn_calib_size.setObjectName(u"btn_calib_size")
        self.btn_calib_size.setGeometry(QRect(130, 40, 111, 33))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(False)
        font1.setWeight(50)
        self.btn_calib_size.setFont(font1)
        self.btn_calib_size.setCursor(QCursor(Qt.PointingHandCursor))
        icon1 = QIcon()
        icon1.addFile(u"GUI/icon_calib.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_calib_size.setIcon(icon1)
        self.btn_calib_size.setAutoDefault(True)
        self.btn_test_size = QPushButton(self.groupBox_10)
        self.btn_test_size.setObjectName(u"btn_test_size")
        self.btn_test_size.setGeometry(QRect(130, 80, 111, 33))
        self.btn_test_size.setFont(font1)
        self.btn_test_size.setCursor(QCursor(Qt.PointingHandCursor))
        icon2 = QIcon()
        icon2.addFile(u"GUI/icon_test.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_test_size.setIcon(icon2)
        self.btn_test_size.setAutoDefault(True)
        self.btn_calib_mode = QPushButton(self.groupBox_10)
        self.btn_calib_mode.setObjectName(u"btn_calib_mode")
        self.btn_calib_mode.setGeometry(QRect(10, 40, 111, 71))
        self.btn_calib_mode.setFont(font1)
        self.btn_calib_mode.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_calib_mode.setStyleSheet(u"background: rgb(235,235,235)")
        self.btn_calib_mode.setAutoDefault(True)
        self.calib_size_view = QLabel(Dialog)
        self.calib_size_view.setObjectName(u"calib_size_view")
        self.calib_size_view.setGeometry(QRect(270, 10, 531, 421))
        self.calib_size_view.setStyleSheet(u"background: transparent;")
        self.calib_size_view.setFrameShape(QFrame.WinPanel)
        self.calib_size_view.setPixmap(QPixmap(u"GUI/load_image.png"))
        self.calib_size_view.setScaledContents(True)
        self.frame_7 = QFrame(Dialog)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(10, 160, 251, 191))
        self.frame_7.setFrameShape(QFrame.WinPanel)
        self.frame_7.setFrameShadow(QFrame.Plain)
        self.label_31 = QLabel(self.frame_7)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 10, 191, 41))
        font2 = QFont()
        font2.setFamily(u"Montserrat")
        font2.setPointSize(10)
        font2.setBold(True)
        font2.setUnderline(False)
        font2.setWeight(75)
        self.label_31.setFont(font2)
        self.label_31.setStyleSheet(u"background: #ff0000\n"
"")
        self.label_31.setFrameShape(QFrame.Box)
        self.label_31.setAlignment(Qt.AlignCenter)
        self.label_32 = QLabel(self.frame_7)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(20, 60, 41, 31))
        font3 = QFont()
        font3.setPointSize(9)
        font3.setBold(True)
        font3.setUnderline(False)
        font3.setWeight(75)
        font3.setStrikeOut(False)
        self.label_32.setFont(font3)
        self.label_32.setStyleSheet(u"background: transparent;")
        self.res_size = QLabel(self.frame_7)
        self.res_size.setObjectName(u"res_size")
        self.res_size.setGeometry(QRect(70, 60, 131, 31))
        font4 = QFont()
        font4.setFamily(u"MS Shell Dlg 2")
        font4.setPointSize(9)
        self.res_size.setFont(font4)
        self.res_size.setFrameShape(QFrame.WinPanel)
        self.res_size.setFrameShadow(QFrame.Sunken)
        self.res_size.setAlignment(Qt.AlignCenter)
        self.lb_info = QLabel(self.frame_7)
        self.lb_info.setObjectName(u"lb_info")
        self.lb_info.setGeometry(QRect(10, 110, 231, 61))
        font5 = QFont()
        font5.setPointSize(9)
        font5.setItalic(False)
        self.lb_info.setFont(font5)
        self.lb_info.setFocusPolicy(Qt.ClickFocus)
        self.lb_info.setStyleSheet(u"")
        self.lb_info.setFrameShape(QFrame.Box)
        self.lb_info.setFrameShadow(QFrame.Raised)
        self.lb_info.setLineWidth(1)
        self.lb_info.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.lb_info.setMargin(1)

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Calibrate size model", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("Dialog", u"Size Calibration", None))
        self.btn_calib_size.setText(QCoreApplication.translate("Dialog", u"Calibrate", None))
        self.btn_test_size.setText(QCoreApplication.translate("Dialog", u"Test", None))
        self.btn_calib_mode.setText(QCoreApplication.translate("Dialog", u"On Mode", None))
        self.calib_size_view.setText("")
        self.label_31.setText(QCoreApplication.translate("Dialog", u"Calibration Results", None))
        self.label_32.setText(QCoreApplication.translate("Dialog", u"Size", None))
        self.res_size.setText(QCoreApplication.translate("Dialog", u"not detect", None))
        self.lb_info.setText("")
    # retranslateUi

