# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui_speed.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(1114, 517)
        icon = QIcon()
        icon.addFile(u"GUI/icon_convey.png", QSize(), QIcon.Normal, QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(218, 211, 204, 240), stop:1 rgba(255, 255, 255, 255))")
        self.frame_5 = QFrame(Dialog)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(10, 10, 1091, 491))
        self.frame_5.setStyleSheet(u"")
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Plain)
        self.groupBox_15 = QGroupBox(self.frame_5)
        self.groupBox_15.setObjectName(u"groupBox_15")
        self.groupBox_15.setGeometry(QRect(10, 20, 491, 201))
        font = QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_15.setFont(font)
        self.groupBox_15.setStyleSheet(u"border: 2px solid;")
        self.txt_setpoint_sp = QTextEdit(self.groupBox_15)
        self.txt_setpoint_sp.setObjectName(u"txt_setpoint_sp")
        self.txt_setpoint_sp.setGeometry(QRect(320, 50, 101, 31))
        font1 = QFont()
        font1.setPointSize(9)
        self.txt_setpoint_sp.setFont(font1)
        self.txt_setpoint_sp.setStyleSheet(u"background: transparent;color:rgb(0, 0, 255)")
        self.txt_setpoint_sp.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_setpoint_sp.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_pv_sp = QTextEdit(self.groupBox_15)
        self.txt_pv_sp.setObjectName(u"txt_pv_sp")
        self.txt_pv_sp.setGeometry(QRect(320, 100, 101, 31))
        self.txt_pv_sp.setFont(font1)
        self.txt_pv_sp.setStyleSheet(u"background: transparent;color:rgb(255, 0, 0)")
        self.txt_pv_sp.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_pv_sp.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_pv_sp.setReadOnly(True)
        self.btn_run_convey = QPushButton(self.groupBox_15)
        self.btn_run_convey.setObjectName(u"btn_run_convey")
        self.btn_run_convey.setGeometry(QRect(20, 40, 141, 51))
        font2 = QFont()
        font2.setPointSize(9)
        font2.setBold(False)
        font2.setWeight(50)
        self.btn_run_convey.setFont(font2)
        self.btn_run_convey.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_run_convey.setIcon(icon)
        self.btn_run_convey.setIconSize(QSize(23, 23))
        self.label_53 = QLabel(self.groupBox_15)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(220, 50, 91, 31))
        font3 = QFont()
        font3.setPointSize(10)
        self.label_53.setFont(font3)
        self.label_53.setStyleSheet(u"background: transparent; color:rgb(0, 0, 255);border:none;")
        self.label_53.setAlignment(Qt.AlignCenter)
        self.label_54 = QLabel(self.groupBox_15)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(170, 100, 141, 31))
        self.label_54.setFont(font3)
        self.label_54.setStyleSheet(u"background: transparent; color:rgb(255, 0, 0);border:none;")
        self.label_54.setAlignment(Qt.AlignCenter)
        self.light_stt_convey_sp = QLabel(self.groupBox_15)
        self.light_stt_convey_sp.setObjectName(u"light_stt_convey_sp")
        self.light_stt_convey_sp.setGeometry(QRect(56, 105, 71, 71))
        self.light_stt_convey_sp.setStyleSheet(u"background: rgb(255,0,0); border-radius:35px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width : 1px;\n"
"border-style:inset;")
        self.label_55 = QLabel(self.groupBox_15)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(430, 50, 51, 31))
        self.label_55.setFont(font3)
        self.label_55.setStyleSheet(u"background: transparent;color:rgb(0, 0, 255);border:none;")
        self.label_55.setAlignment(Qt.AlignCenter)
        self.label_56 = QLabel(self.groupBox_15)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(430, 100, 51, 31))
        self.label_56.setFont(font3)
        self.label_56.setStyleSheet(u"background: transparent;color:rgb(255, 0, 0);border:none;")
        self.label_56.setAlignment(Qt.AlignCenter)
        self.groupBox_16 = QGroupBox(self.frame_5)
        self.groupBox_16.setObjectName(u"groupBox_16")
        self.groupBox_16.setGeometry(QRect(10, 240, 491, 151))
        self.groupBox_16.setFont(font)
        self.groupBox_16.setStyleSheet(u"border: 2px solid;")
        self.label_58 = QLabel(self.groupBox_16)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(20, 30, 91, 51))
        self.label_58.setFont(font1)
        self.label_58.setStyleSheet(u"background:transparent;border:none;")
        self.cb_low_area = QComboBox(self.groupBox_16)
        self.cb_low_area.setObjectName(u"cb_low_area")
        self.cb_low_area.setGeometry(QRect(120, 40, 73, 31))
        self.cb_low_area.setFont(font2)
        self.cb_high_area = QComboBox(self.groupBox_16)
        self.cb_high_area.setObjectName(u"cb_high_area")
        self.cb_high_area.setGeometry(QRect(220, 40, 73, 31))
        self.cb_high_area.setFont(font2)
        self.label_59 = QLabel(self.groupBox_16)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(190, 30, 31, 51))
        font4 = QFont()
        font4.setPointSize(13)
        font4.setBold(True)
        font4.setWeight(75)
        self.label_59.setFont(font4)
        self.label_59.setStyleSheet(u"background:transparent;border:none;")
        self.label_59.setAlignment(Qt.AlignCenter)
        self.label_60 = QLabel(self.groupBox_16)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(20, 90, 111, 31))
        self.label_60.setFont(font1)
        self.label_60.setStyleSheet(u"background:transparent;border:none;")
        self.label_61 = QLabel(self.groupBox_16)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(300, 40, 41, 31))
        self.label_61.setFont(font1)
        self.label_61.setStyleSheet(u"background:transparent;border:none;")
        self.txt_convey_sp_rf = QTextEdit(self.groupBox_16)
        self.txt_convey_sp_rf.setObjectName(u"txt_convey_sp_rf")
        self.txt_convey_sp_rf.setGeometry(QRect(140, 90, 81, 31))
        self.txt_convey_sp_rf.setFont(font1)
        self.txt_convey_sp_rf.setStyleSheet(u"background: transparent;color:rgb(0, 0, 255)")
        self.txt_convey_sp_rf.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_convey_sp_rf.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_convey_sp_rf.setReadOnly(True)
        self.label_62 = QLabel(self.groupBox_16)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(230, 90, 91, 31))
        self.label_62.setFont(font1)
        self.label_62.setStyleSheet(u"background:transparent;border:none;")
        self.btn_apply_rf = QPushButton(self.groupBox_16)
        self.btn_apply_rf.setObjectName(u"btn_apply_rf")
        self.btn_apply_rf.setGeometry(QRect(350, 30, 121, 41))
        self.btn_apply_rf.setFont(font2)
        self.btn_apply_rf.setCursor(QCursor(Qt.PointingHandCursor))
        self.txt_info_convey_rf = QLabel(self.groupBox_16)
        self.txt_info_convey_rf.setObjectName(u"txt_info_convey_rf")
        self.txt_info_convey_rf.setGeometry(QRect(350, 80, 121, 41))
        self.txt_info_convey_rf.setFont(font1)
        self.txt_info_convey_rf.setStyleSheet(u"border:none;")
        self.txt_info_convey_rf.setFrameShape(QFrame.NoFrame)
        self.txt_info_convey_rf.setFrameShadow(QFrame.Raised)
        self.txt_info_convey_rf.setLineWidth(1)
        self.txt_info_convey_rf.setAlignment(Qt.AlignCenter)
        self.graphicsView = QGraphicsView(self.frame_5)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(510, 20, 551, 371))
        self.graphicsView.setStyleSheet(u"border: 1px solid;")
        self.graphicsView.setFrameShape(QFrame.Box)
        self.graphicsView.setFrameShadow(QFrame.Raised)
        self.graphicsView.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.label_57 = QLabel(self.frame_5)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(960, 400, 101, 31))
        self.label_57.setFont(font3)
        self.label_57.setStyleSheet(u"background: transparent; color:rgb(0, 0, 255)")
        self.label_57.setAlignment(Qt.AlignCenter)
        self.label_63 = QLabel(self.frame_5)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(930, 430, 131, 31))
        self.label_63.setFont(font3)
        self.label_63.setStyleSheet(u"background: transparent; color:rgb(255, 0, 0)")
        self.label_63.setAlignment(Qt.AlignCenter)
        self.btn_clear_graph = QPushButton(self.frame_5)
        self.btn_clear_graph.setObjectName(u"btn_clear_graph")
        self.btn_clear_graph.setGeometry(QRect(510, 400, 93, 31))

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Control conveyor speed", None))
        self.groupBox_15.setTitle(QCoreApplication.translate("Dialog", u"Speed Control", None))
        self.txt_setpoint_sp.setHtml(QCoreApplication.translate("Dialog", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.txt_pv_sp.setHtml(QCoreApplication.translate("Dialog", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.btn_run_convey.setText(QCoreApplication.translate("Dialog", u"Start Conveyor", None))
        self.label_53.setText(QCoreApplication.translate("Dialog", u"Set Speed:", None))
        self.label_54.setText(QCoreApplication.translate("Dialog", u"Current Speed:", None))
        self.light_stt_convey_sp.setText("")
        self.label_55.setText(QCoreApplication.translate("Dialog", u"cm/s", None))
        self.label_56.setText(QCoreApplication.translate("Dialog", u"cm/s", None))
        self.groupBox_16.setTitle(QCoreApplication.translate("Dialog", u"Apply Conveyor Speed to Auto Mode", None))
        self.label_58.setText(QCoreApplication.translate("Dialog", u"Working Area:", None))
        self.label_59.setText(QCoreApplication.translate("Dialog", u"-", None))
        self.label_60.setText(QCoreApplication.translate("Dialog", u"Conveyor Speed:", None))
        self.label_61.setText(QCoreApplication.translate("Dialog", u"(cm)", None))
        self.txt_convey_sp_rf.setHtml(QCoreApplication.translate("Dialog", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3</p></body></html>", None))
        self.label_62.setText(QCoreApplication.translate("Dialog", u"(cm per sec)", None))
        self.btn_apply_rf.setText(QCoreApplication.translate("Dialog", u"Apply", None))
        self.txt_info_convey_rf.setText("")
        self.label_57.setText(QCoreApplication.translate("Dialog", u"Set Speed ---", None))
        self.label_63.setText(QCoreApplication.translate("Dialog", u"Current Speed ---", None))
        self.btn_clear_graph.setText(QCoreApplication.translate("Dialog", u"Clear", None))
    # retranslateUi

