# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui_camera.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_CameraDialog(object):
    def setupUi(self, CameraDialog):
        if not CameraDialog.objectName():
            CameraDialog.setObjectName(u"CameraDialog")
        CameraDialog.resize(1160, 808)
        icon = QIcon()
        icon.addFile(u"GUI/icon_tools.png", QSize(), QIcon.Normal, QIcon.Off)
        CameraDialog.setWindowIcon(icon)
        CameraDialog.setStyleSheet(u"background-color:qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(218, 211, 204, 240), stop:1 rgba(255, 255, 255, 255))")
        self.frame_8 = QFrame(CameraDialog)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(10, 10, 341, 651))
        self.frame_8.setStyleSheet(u"")
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Plain)
        self.groupBox_11 = QGroupBox(self.frame_8)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(10, 310, 311, 171))
        font = QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setStyleSheet(u"color: rgb(0,0,255);border: 2px solid;background:rgb(223, 223, 223)")
        self.cb_calib_model = QComboBox(self.groupBox_11)
        self.cb_calib_model.setObjectName(u"cb_calib_model")
        self.cb_calib_model.setGeometry(QRect(100, 30, 181, 31))
        font1 = QFont()
        font1.setPointSize(9)
        font1.setBold(False)
        font1.setWeight(50)
        self.cb_calib_model.setFont(font1)
        self.cb_calib_model.setStyleSheet(u"color: black;")
        self.label_44 = QLabel(self.groupBox_11)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(10, 30, 71, 31))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(False)
        font2.setWeight(50)
        self.label_44.setFont(font2)
        self.label_44.setStyleSheet(u"background: transparent;color: black; border:none;")
        self.btn_apply_calib_model = QPushButton(self.groupBox_11)
        self.btn_apply_calib_model.setObjectName(u"btn_apply_calib_model")
        self.btn_apply_calib_model.setGeometry(QRect(130, 120, 121, 31))
        font3 = QFont()
        font3.setBold(False)
        font3.setWeight(50)
        self.btn_apply_calib_model.setFont(font3)
        self.btn_apply_calib_model.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_apply_calib_model.setStyleSheet(u"color :black;")
        self.label_45 = QLabel(self.groupBox_11)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(10, 70, 71, 31))
        self.label_45.setFont(font2)
        self.label_45.setStyleSheet(u"background: transparent;color: black; border:none;")
        self.cb_calib_model_in = QComboBox(self.groupBox_11)
        self.cb_calib_model_in.setObjectName(u"cb_calib_model_in")
        self.cb_calib_model_in.setGeometry(QRect(100, 70, 181, 31))
        self.cb_calib_model_in.setFont(font1)
        self.cb_calib_model_in.setStyleSheet(u"color: black;")
        self.groupBox_12 = QGroupBox(self.frame_8)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(10, 500, 311, 121))
        self.groupBox_12.setFont(font)
        self.groupBox_12.setStyleSheet(u"border: 2px solid;background:rgb(210, 210, 210)")
        self.btn_on_cam_test = QPushButton(self.groupBox_12)
        self.btn_on_cam_test.setObjectName(u"btn_on_cam_test")
        self.btn_on_cam_test.setGeometry(QRect(10, 30, 91, 71))
        font4 = QFont()
        font4.setPointSize(14)
        font4.setBold(False)
        font4.setWeight(50)
        self.btn_on_cam_test.setFont(font4)
        self.btn_on_cam_test.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_on_cam_test.setStyleSheet(u"background: rgb(235,235,235)")
        self.btn_on_cam_test.setAutoDefault(True)
        self.slide_points_test = QSlider(self.groupBox_12)
        self.slide_points_test.setObjectName(u"slide_points_test")
        self.slide_points_test.setGeometry(QRect(120, 70, 171, 21))
        font5 = QFont()
        font5.setPointSize(8)
        self.slide_points_test.setFont(font5)
        self.slide_points_test.setStyleSheet(u"background: transparent;border:none;")
        self.slide_points_test.setMinimum(5)
        self.slide_points_test.setMaximum(15)
        self.slide_points_test.setOrientation(Qt.Horizontal)
        self.label_39 = QLabel(self.groupBox_12)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(120, 30, 171, 31))
        self.label_39.setFont(font1)
        self.label_39.setStyleSheet(u"background:transparent; border:none;")
        self.groupBox_9 = QGroupBox(self.frame_8)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(10, 110, 311, 181))
        self.groupBox_9.setFont(font)
        self.groupBox_9.setStyleSheet(u"color: rgb(255,0,0);border: 2px solid;background: rgb(231, 231, 231)")
        self.btn_calib_mode_cam = QPushButton(self.groupBox_9)
        self.btn_calib_mode_cam.setObjectName(u"btn_calib_mode_cam")
        self.btn_calib_mode_cam.setGeometry(QRect(10, 30, 91, 71))
        self.btn_calib_mode_cam.setFont(font2)
        self.btn_calib_mode_cam.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_calib_mode_cam.setStyleSheet(u"background: rgb(235,235,235); color: rgb(0,0,0);")
        self.btn_calib_mode_cam.setAutoDefault(True)
        self.btn_scrshot = QPushButton(self.groupBox_9)
        self.btn_scrshot.setObjectName(u"btn_scrshot")
        self.btn_scrshot.setGeometry(QRect(10, 140, 91, 31))
        font6 = QFont()
        font6.setPointSize(8)
        font6.setBold(False)
        font6.setWeight(50)
        self.btn_scrshot.setFont(font6)
        self.btn_scrshot.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_scrshot.setStyleSheet(u"color: rgb(0,0,0);")
        icon1 = QIcon()
        icon1.addFile(u"GUI/icon_scnshot.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_scrshot.setIcon(icon1)
        self.btn_calib_cam = QPushButton(self.groupBox_9)
        self.btn_calib_cam.setObjectName(u"btn_calib_cam")
        self.btn_calib_cam.setGeometry(QRect(110, 140, 91, 31))
        self.btn_calib_cam.setFont(font3)
        self.btn_calib_cam.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_calib_cam.setStyleSheet(u"color: rgb(0,0,0);")
        icon2 = QIcon()
        icon2.addFile(u"GUI/icon_calib.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_calib_cam.setIcon(icon2)
        self.btn_save_model = QPushButton(self.groupBox_9)
        self.btn_save_model.setObjectName(u"btn_save_model")
        self.btn_save_model.setGeometry(QRect(210, 140, 91, 31))
        self.btn_save_model.setFont(font3)
        self.btn_save_model.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_save_model.setStyleSheet(u"color: rgb(0,0,0);")
        icon3 = QIcon()
        icon3.addFile(u"GUI/icon_save.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_save_model.setIcon(icon3)
        self.label_47 = QLabel(self.groupBox_9)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(130, 30, 171, 21))
        font7 = QFont()
        font7.setFamily(u"Arial Narrow")
        font7.setPointSize(8)
        font7.setBold(True)
        font7.setItalic(False)
        font7.setWeight(75)
        self.label_47.setFont(font7)
        self.label_47.setStyleSheet(u"background: transparent;color: rgb(0,0,0);border:none;")
        self.txt_name_calib_model = QTextEdit(self.groupBox_9)
        self.txt_name_calib_model.setObjectName(u"txt_name_calib_model")
        self.txt_name_calib_model.setGeometry(QRect(130, 60, 171, 31))
        self.txt_name_calib_model.setFont(font3)
        self.txt_name_calib_model.viewport().setProperty("cursor", QCursor(Qt.IBeamCursor))
        self.txt_name_calib_model.setStyleSheet(u"background: #FFFFFF")
        self.txt_name_calib_model.setFrameShape(QFrame.WinPanel)
        self.txt_name_calib_model.setFrameShadow(QFrame.Sunken)
        self.txt_name_calib_model.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_name_calib_model.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_name_calib_model.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.cb_intrinsic_extrinsic = QComboBox(self.groupBox_9)
        self.cb_intrinsic_extrinsic.addItem("")
        self.cb_intrinsic_extrinsic.addItem("")
        self.cb_intrinsic_extrinsic.setObjectName(u"cb_intrinsic_extrinsic")
        self.cb_intrinsic_extrinsic.setGeometry(QRect(130, 100, 171, 31))
        self.cb_intrinsic_extrinsic.setFont(font1)
        self.cb_intrinsic_extrinsic.setStyleSheet(u"color: black;")
        self.label_51 = QLabel(self.frame_8)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(20, 20, 91, 31))
        font8 = QFont()
        font8.setPointSize(10)
        font8.setBold(True)
        font8.setWeight(75)
        self.label_51.setFont(font8)
        self.label_51.setStyleSheet(u"background: transparent;")
        self.cb_opt_calib_cam_2 = QComboBox(self.frame_8)
        self.cb_opt_calib_cam_2.setObjectName(u"cb_opt_calib_cam_2")
        self.cb_opt_calib_cam_2.setGeometry(QRect(120, 20, 201, 31))
        font9 = QFont()
        font9.setPointSize(9)
        self.cb_opt_calib_cam_2.setFont(font9)
        self.cb_opt_calib_cam_2.setStyleSheet(u"")
        self.lb_opt_calib_cam_2 = QLabel(self.frame_8)
        self.lb_opt_calib_cam_2.setObjectName(u"lb_opt_calib_cam_2")
        self.lb_opt_calib_cam_2.setGeometry(QRect(120, 60, 201, 31))
        font10 = QFont()
        font10.setFamily(u"Noto Sans")
        font10.setPointSize(9)
        font10.setBold(True)
        font10.setItalic(False)
        font10.setWeight(75)
        self.lb_opt_calib_cam_2.setFont(font10)
        self.lb_opt_calib_cam_2.setStyleSheet(u"color: rgb(0,0,255);")
        self.lb_opt_calib_cam_2.setFrameShape(QFrame.NoFrame)
        self.lb_opt_calib_cam_2.setFrameShadow(QFrame.Raised)
        self.lb_opt_calib_cam_2.setAlignment(Qt.AlignCenter)
        self.label_17 = QLabel(CameraDialog)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 700, 341, 71))
        font11 = QFont()
        font11.setPointSize(10)
        font11.setBold(True)
        font11.setItalic(False)
        font11.setUnderline(False)
        font11.setWeight(75)
        self.label_17.setFont(font11)
        self.label_17.setStyleSheet(u"color: rgb(255,0,0);\n"
"")
        self.label_17.setFrameShape(QFrame.Box)
        self.label_17.setTextFormat(Qt.AutoText)
        self.label_17.setScaledContents(True)
        self.label_17.setAlignment(Qt.AlignCenter)
        self.label_17.setWordWrap(True)
        self.label_52 = QLabel(CameraDialog)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(360, 670, 181, 131))
        self.label_52.setPixmap(QPixmap(u"GUI/img_ex_checkerboard.png"))
        self.label_52.setScaledContents(True)
        self.frame = QFrame(CameraDialog)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(360, 10, 791, 651))
        self.frame.setStyleSheet(u"")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Plain)
        self.gridLayoutWidget = QWidget(self.frame)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(50, 60, 711, 531))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.calib_cam_view = QLabel(self.gridLayoutWidget)
        self.calib_cam_view.setObjectName(u"calib_cam_view")
        self.calib_cam_view.setFrameShape(QFrame.WinPanel)
        self.calib_cam_view.setPixmap(QPixmap(u"GUI/load_image.png"))
        self.calib_cam_view.setScaledContents(True)

        self.gridLayout.addWidget(self.calib_cam_view, 0, 0, 1, 1)

        self.label_46 = QLabel(self.frame)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(50, 10, 711, 51))
        font12 = QFont()
        font12.setFamily(u"Barlow Condensed Light")
        font12.setPointSize(13)
        font12.setBold(True)
        font12.setWeight(75)
        self.label_46.setFont(font12)
        self.label_46.setStyleSheet(u"background:transparent;")
        self.label_46.setAlignment(Qt.AlignCenter)
        self.txt_info_calib_cam = QLabel(self.frame)
        self.txt_info_calib_cam.setObjectName(u"txt_info_calib_cam")
        self.txt_info_calib_cam.setGeometry(QRect(50, 600, 711, 31))
        font13 = QFont()
        font13.setFamily(u"Noto Serif")
        font13.setPointSize(10)
        font13.setBold(True)
        font13.setWeight(75)
        self.txt_info_calib_cam.setFont(font13)
        self.txt_info_calib_cam.setStyleSheet(u"background: transparent")
        self.txt_info_calib_cam.setFrameShape(QFrame.WinPanel)
        self.txt_info_calib_cam.setFrameShadow(QFrame.Sunken)

        self.retranslateUi(CameraDialog)

        QMetaObject.connectSlotsByName(CameraDialog)
    # setupUi

    def retranslateUi(self, CameraDialog):
        CameraDialog.setWindowTitle(QCoreApplication.translate("CameraDialog", u"Calibrate the camera", None))
        self.groupBox_11.setTitle(QCoreApplication.translate("CameraDialog", u"Pretrained Calib Model", None))
        self.label_44.setText(QCoreApplication.translate("CameraDialog", u"Extrinsic:", None))
        self.btn_apply_calib_model.setText(QCoreApplication.translate("CameraDialog", u"Apply", None))
        self.label_45.setText(QCoreApplication.translate("CameraDialog", u"Intrinsic:", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("CameraDialog", u"Test Model", None))
        self.btn_on_cam_test.setText(QCoreApplication.translate("CameraDialog", u"ON", None))
        self.label_39.setText(QCoreApplication.translate("CameraDialog", u"Inc/Dec points:", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("CameraDialog", u"Customize New Model", None))
        self.btn_calib_mode_cam.setText(QCoreApplication.translate("CameraDialog", u"On Mode", None))
        self.btn_scrshot.setText(QCoreApplication.translate("CameraDialog", u" PrtSc", None))
        self.btn_calib_cam.setText(QCoreApplication.translate("CameraDialog", u"Calibrate", None))
        self.btn_save_model.setText(QCoreApplication.translate("CameraDialog", u"Save", None))
        self.label_47.setText(QCoreApplication.translate("CameraDialog", u"Insert name of new model:", None))
        self.cb_intrinsic_extrinsic.setItemText(0, QCoreApplication.translate("CameraDialog", u"Extrinsic Params", None))
        self.cb_intrinsic_extrinsic.setItemText(1, QCoreApplication.translate("CameraDialog", u"Intrinsic Params", None))

        self.label_51.setText(QCoreApplication.translate("CameraDialog", u"OPTION:", None))
        self.lb_opt_calib_cam_2.setText(QCoreApplication.translate("CameraDialog", u"Use pretrained model", None))
        self.label_17.setText(QCoreApplication.translate("CameraDialog", u"Insert the checkerboard (8x6) to\n"
"calibrate the camera", None))
        self.label_52.setText("")
        self.calib_cam_view.setText("")
        self.label_46.setText(QCoreApplication.translate("CameraDialog", u"Calibration View", None))
        self.txt_info_calib_cam.setText("")
    # retranslateUi

